import { ExternalLink, FileSearch, Link2Off } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { listSources } from "@/lib/repositories/admin";

export const dynamic = "force-dynamic";
export default async function SourcesPage() {
  const items = await listSources();
  return <div><p className="text-xs font-semibold text-primary">内容治理</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">来源与采集记录</h1><p className="mt-2 text-sm text-muted-foreground">集中查看规范化来源、可访问状态、正文哈希和关联案例。来源失效不会自动删除案例。</p>{items.length ? <div className="mt-7 space-y-3">{items.map((item) => <Card key={item.id} className="py-0 shadow-none"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-start"><span className="grid size-10 shrink-0 place-items-center rounded-xl border text-primary">{item.accessibility === "available" ? <FileSearch className="size-4" /> : <Link2Off className="size-4" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-medium">{item.title}</h2><Badge variant={item.accessibility === "available" ? "default" : "secondary"}>{item.accessibility}</Badge><Badge variant="outline">{item.type}</Badge>{item.snapshotKey && <Badge variant="secondary">私有快照</Badge>}</div><p className="mt-2 text-xs text-muted-foreground">{item.publisher} · 关联 {item.caseIds?.length ?? 0} 个案例 · 最近采集 {new Intl.DateTimeFormat("zh-CN").format(new Date(item.lastCollectedAt))}</p><div className="mt-3 space-y-1 font-mono text-[11px] text-muted-foreground">{item.normalizedUrl && <p className="truncate">URL：{item.normalizedUrl}</p>}{item.externalId && <p>外部编号：{item.externalId}</p>}{item.contentHash && <p className="truncate">SHA-256：{item.contentHash}</p>}</div></div><div className="flex gap-2">{item.snapshotKey && <Button variant="outline" size="sm" asChild><a href={`/api/admin/sources/${item.id}/snapshot`} target="_blank">快照<ExternalLink /></a></Button>}{item.originalUrl && <Button variant="outline" size="sm" asChild><a href={item.originalUrl} target="_blank" rel="noreferrer">原文<ExternalLink /></a></Button>}</div></CardContent></Card>)}</div> : <div className="mt-8 grid min-h-72 place-items-center rounded-2xl border border-dashed text-center"><div><FileSearch className="mx-auto size-9 text-muted-foreground" /><h2 className="mt-4 font-semibold">暂无正式来源</h2><p className="mt-2 text-sm text-muted-foreground">完成数据库配置并导入来源后，这里会显示精确去重记录。</p></div></div>}</div>;
}
