import { NextResponse } from "next/server";
import { createDeepSeek, type DeepSeekLanguageModelOptions } from "@ai-sdk/deepseek";
import { generateText, Output } from "ai";
import { z } from "zod";
import { getAdminSession } from "@/lib/auth/dal";
import { env } from "@/lib/env";
const inputSchema = z.object({ sourceText: z.string().min(30).max(50_000) });
const outputSchema = z.object({ title: z.string(), organization: z.string(), organizationSize: z.string(), industry: z.string(), scenario: z.string(), businessFunction: z.string(), summary: z.string(), background: z.string(), problem: z.string(), solution: z.string(), implementationSteps: z.array(z.string()), duration: z.string(), cost: z.string(), roi: z.string(), results: z.array(z.object({ label: z.string(), value: z.string(), kind: z.enum(["actual", "expected", "estimated", "undisclosed"]) })), risks: z.string(), outcomeStatus: z.enum(["success", "partial", "failure", "undisclosed"]), confidence: z.enum(["high", "medium", "pending"]), sourceTitle: z.string(), sourcePublisher: z.string(), sourceSupports: z.array(z.string()), editorComment: z.string(), suitableFor: z.string(), prerequisites: z.string() });
export async function POST(request: Request) { const session = await getAdminSession(); if (!session) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); if (!env.DEEPSEEK_API_KEY) return NextResponse.json({ error: "DeepSeek 尚未配置" }, { status: 503 }); const parsed = inputSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "请粘贴至少 30 个字的来源材料" }, { status: 400 }); const deepseek = createDeepSeek({ apiKey: env.DEEPSEEK_API_KEY }); try { const { output } = await generateText({ model: deepseek(env.AI_MODEL), output: Output.object({ schema: outputSchema }), system: "你是企业AI案例编辑。将来源整理为中文结构化字段。不得推测成本、周期、效果和ROI：原文未明确披露必须写‘未披露’。行业仅返回 manufacturing, retail, foreign-trade, logistics, finance, healthcare, education, software-internet 之一；场景仅返回 ocr, customer-service, knowledge-base, sales, quotation, workflow, quality-inspection, forecast, content-generation, agent 之一。失败结论必须有明确证据，否则 outcomeStatus=undisclosed。输出 json。", prompt: parsed.data.sourceText, providerOptions: { deepseek: { thinking: { type: "enabled" }, reasoningEffort: "max" } satisfies DeepSeekLanguageModelOptions }, maxOutputTokens: 14_000, abortSignal: AbortSignal.timeout(90_000) }); return NextResponse.json({ ok: true, fields: output }); } catch { return NextResponse.json({ error: "DeepSeek 结构化失败，请检查来源内容后重试" }, { status: 502 }); } }
