import { NextResponse } from "next/server";
import { z } from "zod";
import { getAdminSession } from "@/lib/auth/dal";
import { writeAuditLog } from "@/lib/audit";
import { getIndustry, getScenario } from "@/lib/catalog";
import { getDb, isMongoConfigured } from "@/lib/db/mongodb";
import { caseInputSchema } from "@/app/api/admin/cases/route";
import type { CaseStudy } from "@/lib/types";
type Params = Promise<{ id: string }>;
export async function PATCH(request: Request, { params }: { params: Params }) { const session = await getAdminSession(); if (!session) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); if (!isMongoConfigured()) return NextResponse.json({ error: "请先配置 MongoDB" }, { status: 503 }); const id = (await params).id; const parsed = caseInputSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "案例字段不完整", fields: parsed.error.flatten().fieldErrors }, { status: 400 }); const industry = getIndustry(parsed.data.industry); const scenario = getScenario(parsed.data.scenario); if (!industry || !scenario) return NextResponse.json({ error: "行业或场景无效" }, { status: 400 }); const db = await getDb(); const collection = db.collection<CaseStudy>("cases"); const before = await collection.findOne({ id }, { projection: { _id: 0 } }); if (!before) return NextResponse.json({ error: "案例不存在" }, { status: 404 }); const value = parsed.data; const updatedAt = new Date().toISOString(); const set: Partial<CaseStudy> = { slug: value.slug || before.slug, title: value.title, organization: { ...before.organization, name: value.organization, size: value.organizationSize }, industry, scenarios: [scenario], businessFunctions: [value.businessFunction], summary: value.summary, background: value.background, problem: value.problem, solution: value.solution, implementationSteps: value.implementationSteps, duration: value.duration, cost: value.cost, roi: value.roi, results: value.results, risks: value.risks, outcomeStatus: value.outcomeStatus, confidence: value.confidence, contentStatus: value.contentStatus, editorComment: { ...before.editorComment, text: value.editorComment, suitableFor: value.suitableFor, prerequisites: value.prerequisites }, sources: [{ ...(before.sources[0] ?? { id: `source-${id}`, type: "media", collectedAt: updatedAt, accessibility: "available" }), title: value.sourceTitle, publisher: value.sourcePublisher, url: value.sourceUrl || undefined, publishedAt: value.sourcePublishedAt || undefined, supports: value.sourceSupports }], updatedAt, publishedAt: value.contentStatus === "published" ? (before.publishedAt || updatedAt) : before.publishedAt };
  await collection.updateOne({ id }, { $set: set }); await writeAuditLog({ actor: session.user?.email ?? "admin", action: "case.update", entityType: "case", entityId: id, before, after: set }); return NextResponse.json({ ok: true, id, slug: set.slug }); }
export async function DELETE(_: Request, { params }: { params: Params }) { const session = await getAdminSession(); if (!session) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); if (!isMongoConfigured()) return NextResponse.json({ error: "请先配置 MongoDB" }, { status: 503 }); const id = z.string().min(1).parse((await params).id); const db = await getDb(); const before = await db.collection<CaseStudy>("cases").findOne({ id }, { projection: { _id: 0 } }); if (!before) return NextResponse.json({ error: "案例不存在" }, { status: 404 }); await db.collection("cases").updateOne({ id }, { $set: { contentStatus: "deleted", deletedAt: new Date().toISOString(), updatedAt: new Date().toISOString() } }); await writeAuditLog({ actor: session.user?.email ?? "admin", action: "case.delete", entityType: "case", entityId: id, before }); return NextResponse.json({ ok: true }); }
