import type { Metadata } from "next";
import Link from "next/link";
import { notFound, permanentRedirect } from "next/navigation";
import { ArrowLeft, ArrowRight, Building2, CalendarDays, CheckCircle2, Clock3, ExternalLink, Quote, ShieldCheck, WalletCards } from "lucide-react";
import { CaseCard } from "@/components/case-card";
import { ReadingTracker } from "@/components/reading-tracker";
import { ConfidenceBadge, OutcomeBadge } from "@/components/status-badges";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { getRelatedCases, resolveCaseRoute } from "@/lib/repositories/cases";

type Params = Promise<{ slug: string }>;
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const route = await resolveCaseRoute((await params).slug); if (route.kind === "redirect") return { alternates: { canonical: `/cases/${route.targetSlug}` }, robots: { index: false, follow: true } }; if (route.kind === "missing") return {}; return { title: route.item.title, description: route.item.summary, alternates: { canonical: `/cases/${route.item.slug}` }, robots: route.kind === "archived" ? { index: false, follow: true, noarchive: true } : undefined }; }

function FactSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="grid gap-4 border-t py-9 sm:grid-cols-[88px_1fr]"><p className="font-mono text-xs text-primary">{number}</p><div><h2 className="text-xl font-semibold tracking-tight">{title}</h2><div className="mt-4 text-[15px] leading-8 text-foreground/80">{children}</div></div></section>; }

export default async function CaseDetailPage({ params }: { params: Params }) {
  const route = await resolveCaseRoute((await params).slug); if (route.kind === "missing") notFound(); if (route.kind === "redirect") permanentRedirect(`/cases/${route.targetSlug}`); const item = route.item;
  if (route.kind === "archived") return <main className="container-page py-20"><div className="mx-auto max-w-2xl rounded-3xl border bg-card p-8 text-center sm:p-12"><Badge variant="secondary">已归档</Badge><h1 className="mt-5 text-3xl font-semibold tracking-tight">{item.title}</h1><p className="mt-4 text-sm leading-7 text-muted-foreground">该案例因来源变化、时效性或内容治理原因已归档，不再参与搜索、推荐和阅读统计。页面保留用于说明历史状态。</p><Button asChild className="mt-7"><Link href="/cases">返回案例库</Link></Button></div></main>;
  const related = await getRelatedCases(item, 3);
  const jsonLd = { "@context": "https://schema.org", "@type": "Article", headline: item.title, description: item.summary, datePublished: item.publishedAt, dateModified: item.updatedAt, author: { "@type": "Organization", name: "AI案例库" }, mainEntityOfPage: `/cases/${item.slug}` };
  return <main><ReadingTracker caseId={item.id} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} />
    <div className="border-b bg-card/45"><div className="container-page py-5"><Button variant="ghost" size="sm" asChild><Link href="/cases"><ArrowLeft />返回案例库</Link></Button></div></div>
    <article className="container-page py-10 sm:py-14 lg:py-18">
      <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_300px] lg:gap-14">
        <div><div className="flex flex-wrap gap-2"><OutcomeBadge status={item.outcomeStatus} /><ConfidenceBadge level={item.confidence} />{item.demo && <Badge variant="secondary">演示数据</Badge>}</div><p className="mt-7 text-xs font-semibold text-primary">{item.industry.displayName} · {item.scenarios.map((scene) => scene.name).join(" / ")}</p><h1 className="mt-3 text-balance text-4xl font-semibold leading-[1.12] tracking-[-0.05em] sm:text-5xl">{item.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{item.summary}</p>
          <div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Building2 className="size-3.5" />{item.organization.name}</span><span className="flex items-center gap-1.5"><CalendarDays className="size-3.5" />发布于 {new Intl.DateTimeFormat("zh-CN", { dateStyle: "long" }).format(new Date(item.publishedAt))}</span><span>阅读 {item.views.toLocaleString("zh-CN")}</span></div>
          <div className="mt-10 grid gap-px overflow-hidden rounded-2xl border bg-border sm:grid-cols-3">{item.results.slice(0, 3).map((metric, metricIndex) => <div key={`${metric.label}-${metricIndex}`} className="bg-card p-5"><p className="text-xs text-muted-foreground">{metric.label}</p><p className="mt-2 text-xl font-semibold tracking-tight">{metric.value}</p><p className="mt-2 text-[11px] text-muted-foreground">{metric.kind === "actual" ? "来源披露" : metric.kind === "estimated" ? "估算" : metric.kind === "expected" ? "预期" : "未披露"}</p></div>)}</div>
          <div className="mt-10"><FactSection number="01" title="业务背景"><p>{item.background}</p></FactSection><FactSection number="02" title="遇到的问题"><p>{item.problem}</p></FactSection><FactSection number="03" title="AI 解决方案"><p>{item.solution}</p>{item.implementationSteps.length > 0 && <ol className="mt-5 space-y-3">{item.implementationSteps.map((step, index) => <li key={step} className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-primary/10 text-xs font-semibold text-primary">{index + 1}</span><span>{step}</span></li>)}</ol>}</FactSection><FactSection number="04" title="实施结果">{item.results.map((metric, metricIndex) => <div key={`${metric.label}-${metricIndex}`} className="flex items-start gap-3 py-1.5"><CheckCircle2 className="mt-1 size-4 shrink-0 text-primary" /><p><strong className="font-medium text-foreground">{metric.label}：</strong>{metric.value}</p></div>)}{item.failureReason && <p className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-900">失败原因：{item.failureReason}</p>}</FactSection><FactSection number="05" title="风险与边界"><p>{item.risks}</p></FactSection></div>
          <section className="mt-4 rounded-2xl border border-primary/20 bg-primary/[0.045] p-6 sm:p-8"><div className="flex items-center gap-2 text-xs font-semibold text-primary"><Quote className="size-4" />编辑点评 · AI 辅助生成并经审核</div><p className="mt-5 text-lg font-medium leading-8">{item.editorComment.text}</p><div className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">适合</p><p className="mt-1.5 leading-6">{item.editorComment.suitableFor}</p></div><div><p className="text-xs text-muted-foreground">前置条件</p><p className="mt-1.5 leading-6">{item.editorComment.prerequisites}</p></div></div></section>
          <section className="mt-12"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">信息来源</h2><Badge variant="outline">{item.sources.length} 个来源</Badge></div><p className="mt-2 text-sm leading-6 text-muted-foreground">页面内容为结构化改写；关键结论应可追溯到以下材料。</p><div className="mt-5 space-y-3">{item.sources.map((source, index) => <Card key={source.id} className="py-0 shadow-none"><CardContent className="flex gap-4 p-5"><span className="font-mono text-xs text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><div className="min-w-0 flex-1"><p className="font-medium">{source.title}</p><p className="mt-1.5 text-xs text-muted-foreground">{source.publisher}{source.publishedAt ? ` · ${source.publishedAt}` : ""}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">支持：{source.supports.join("、")}</p></div>{source.url && <Button variant="outline" size="icon" asChild><a href={source.url} target="_blank" rel="noreferrer" aria-label="查看原文"><ExternalLink /></a></Button>}</CardContent></Card>)}</div></section>
        </div>
        <aside className="lg:sticky lg:top-24 lg:self-start"><Card className="shadow-none"><CardContent className="space-y-5"><h2 className="font-semibold">实施概览</h2><Separator />{[{ icon: Building2, label: "企业规模", value: item.organization.size }, { icon: Clock3, label: "实施周期", value: item.duration }, { icon: WalletCards, label: "投入成本", value: item.cost }, { icon: ShieldCheck, label: "ROI", value: item.roi }].map(({ icon: Icon, label, value }) => <div key={label} className="flex gap-3"><Icon className="mt-0.5 size-4 shrink-0 text-primary" /><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium leading-6">{value}</p></div></div>)}<Separator /><div><p className="text-xs text-muted-foreground">业务部门</p><div className="mt-2 flex flex-wrap gap-1.5">{item.businessFunctions.map((value) => <Badge key={value} variant="secondary">{value}</Badge>)}</div></div><Button className="w-full" asChild><Link href="/assessment">评估我的企业<ArrowRight /></Link></Button></CardContent></Card>
          <p className="mt-4 px-2 text-[11px] leading-5 text-muted-foreground">案例用于经验参考，不构成采购、投资或效果承诺。</p><Button variant="ghost" size="sm" asChild className="mt-2 w-full text-xs text-muted-foreground"><Link href={`/contact?type=correction&case=${item.id}`}>发现信息有误？提交更正</Link></Button>
        </aside>
      </div>
    </article>
    {related.length > 0 && <section className="border-t bg-card/45"><div className="container-page py-16"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold text-primary">继续阅读</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">相关案例</h2></div><Button variant="outline" asChild><Link href={`/cases?industry=${item.industry.slug}`}>更多{item.industry.displayName}案例<ArrowRight /></Link></Button></div><div className="mt-7 grid gap-4 md:grid-cols-3">{related.map((entry) => <CaseCard key={entry.id} caseStudy={entry} />)}</div></div></section>}
  </main>;
}
