import Link from "next/link";
import { Edit3, Plus } from "lucide-react";
import { OutcomeBadge } from "@/components/status-badges";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { listAdminCases } from "@/lib/repositories/admin";
const statusMap: Record<string, string> = { draft: "草稿", duplicate_review: "重复复核", in_review: "内容审核", published: "已发布", rejected: "已退回", archived: "已归档", merged: "已合并" };
export default async function AdminCasesPage() { const cases = await listAdminCases(); return <div><div className="flex items-end justify-between"><div><p className="text-xs font-semibold text-primary">内容管理</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">案例</h1><p className="mt-2 text-sm text-muted-foreground">共 {cases.length} 条当前可见记录</p></div><Button asChild><Link href="/admin/cases/new"><Plus />新建案例</Link></Button></div><Card className="mt-7 py-0 shadow-none"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>案例</TableHead><TableHead>企业 / 行业</TableHead><TableHead>结果</TableHead><TableHead>状态</TableHead><TableHead>更新时间</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{cases.map((item) => <TableRow key={item.id}><TableCell className="max-w-md"><p className="line-clamp-2 font-medium">{item.title}</p>{item.demo && <Badge variant="secondary" className="mt-1">演示</Badge>}</TableCell><TableCell><p className="text-sm">{item.organization.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.industry.displayName}</p></TableCell><TableCell><OutcomeBadge status={item.outcomeStatus} /></TableCell><TableCell><Badge variant="outline">{statusMap[item.contentStatus] ?? item.contentStatus}</Badge></TableCell><TableCell className="text-xs text-muted-foreground">{new Intl.DateTimeFormat("zh-CN").format(new Date(item.updatedAt))}</TableCell><TableCell className="text-right"><Button variant="ghost" size="icon" asChild><Link href={`/admin/cases/${item.id}`} aria-label="编辑案例"><Edit3 /></Link></Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>; }
