import { NextResponse } from "next/server";
import { parse } from "csv-parse/sync";
import { nanoid } from "nanoid";
import { z } from "zod";
import { getAdminSession } from "@/lib/auth/dal";
import { writeAuditLog } from "@/lib/audit";
import { contentHash, duplicateLevel, normalizeContent, normalizeOrganization, normalizeUrl, scoreDuplicate, type IncomingCase } from "@/lib/dedup";
import { getDb, isMongoConfigured } from "@/lib/db/mongodb";
import { listAdminCases } from "@/lib/repositories/admin";
import type { DuplicateCandidate } from "@/lib/types";

const requestSchema = z.object({ format: z.enum(["json", "csv"]), content: z.string().min(2).max(2_000_000) });
const rowSchema = z.object({ title: z.string().min(2).max(300), organization: z.string().min(1).max(200), sourceUrl: z.string().max(2000).optional().default(""), sourceTitle: z.string().max(300).optional().default(""), publishedAt: z.string().max(50).optional().default(""), scenario: z.string().max(100).optional().default(""), department: z.string().max(100).optional().default(""), implementer: z.string().max(200).optional().default(""), solution: z.string().max(5000).optional().default(""), result: z.string().max(2000).optional().default(""), rawText: z.string().max(50_000).optional().default("") });
function parseRows(format: "json" | "csv", content: string) { const raw: unknown[] = format === "json" ? (Array.isArray(JSON.parse(content)) ? JSON.parse(content) : [JSON.parse(content)]) : parse(content, { columns: true, skip_empty_lines: true, bom: true, trim: true }); return raw.slice(0, 200).map((value, index) => ({ index: index + 1, parsed: rowSchema.safeParse(value) })); }
export async function POST(request: Request) { const session = await getAdminSession(); if (!session) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); const parsedRequest = requestSchema.safeParse(await request.json().catch(() => null)); if (!parsedRequest.success) return NextResponse.json({ error: "导入内容无效" }, { status: 400 }); let parsedRows; try { parsedRows = parseRows(parsedRequest.data.format, parsedRequest.data.content); } catch { return NextResponse.json({ error: "无法解析文件，请检查 JSON 或 CSV 格式" }, { status: 400 }); } const existingCases = await listAdminCases(500); const jobId = nanoid(14); const results: Array<Record<string, unknown>> = []; const db = isMongoConfigured() ? await getDb() : null;
  for (const entry of parsedRows) { if (!entry.parsed.success) { results.push({ row: entry.index, status: "invalid", error: entry.parsed.error.issues[0]?.message }); continue; } const row: IncomingCase = entry.parsed.data; const normalized = normalizeUrl(row.sourceUrl); const raw = row.rawText || [row.title, row.organization, row.sourceTitle, row.solution, row.result].join("\n"); const hash = contentHash(raw); const idempotencyKey = normalized ? `url:${normalized}` : `hash:${hash}`;
    if (db) { const previous = await db.collection("import_rows").findOne({ idempotencyKey }); if (previous) { await db.collection("import_rows").updateOne({ _id: previous._id }, { $set: { lastSeenAt: new Date(), raw }, $inc: { seenCount: 1 } }); results.push({ row: entry.index, title: row.title, status: "exact_duplicate", message: "相同来源已更新采集记录，未重复插入" }); continue; } }
    const candidates = existingCases.map((item) => ({ item, scores: scoreDuplicate(row, item) })).sort((a, b) => b.scores.overall - a.scores.overall); const best = candidates[0]; const level = duplicateLevel(best?.scores.overall ?? 0); const importRowId = nanoid(16); const status = level === "high" ? "blocked_duplicate" : level === "medium" ? "needs_duplicate_review" : "staged"; const document = { id: importRowId, jobId, rowNumber: entry.index, ...row, normalizedUrl: normalized, contentHash: hash, idempotencyKey, organizationNormalized: normalizeOrganization(row.organization), normalizedText: normalizeContent(raw), status, extractionStatus: "pending", createdAt: new Date(), lastSeenAt: new Date(), seenCount: 1 };
    if (db) { await db.collection("import_rows").insertOne(document); if (best && level !== "low") { const candidate: DuplicateCandidate & { importRowId: string } = { id: nanoid(16), importRowId, incomingTitle: row.title, incomingOrganization: row.organization, existingCaseId: best.item.id, existingCaseTitle: best.item.title, scores: best.scores, status: "pending", createdAt: new Date().toISOString() }; await db.collection("duplicate_candidates").insertOne(candidate); } }
    results.push({ row: entry.index, title: row.title, status, level, score: best?.scores.overall ?? 0, candidate: best ? { id: best.item.id, title: best.item.title, organization: best.item.organization.name } : null });
  }
  if (db) { await db.collection("import_jobs").insertOne({ id: jobId, format: parsedRequest.data.format, total: parsedRows.length, status: "staged", createdBy: session.user?.email, createdAt: new Date() }); await writeAuditLog({ actor: session.user?.email ?? "admin", action: "import.create", entityType: "import_job", entityId: jobId, metadata: { total: parsedRows.length } }); }
  return NextResponse.json({ ok: true, jobId, persisted: Boolean(db), total: parsedRows.length, results }); }
