"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { LoaderCircle, MessageSquareText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
const options = [{ value: "new", label: "新提交" }, { value: "pending", label: "待联系" }, { value: "contacted", label: "已联系" }, { value: "completed", label: "已完成" }, { value: "invalid", label: "无效" }, { value: "cancelled", label: "已取消" }];
export function AppointmentStatus({ id, value, initialNote = "" }: { id: string; value: string; initialNote?: string }) { const router = useRouter(); const [current, setCurrent] = useState(value); const [note, setNote] = useState(initialNote); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); async function update(next: string) { const previous = current; setCurrent(next); const response = await fetch(`/api/admin/appointments/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: next }) }); if (response.ok) router.refresh(); else setCurrent(previous); } async function saveNote() { setSaving(true); setError(""); const response = await fetch(`/api/admin/appointments/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ note }) }).catch(() => null); if (response?.ok) { setOpen(false); router.refresh(); } else setError((await response?.json().catch(() => null))?.error ?? "备注保存失败"); setSaving(false); } return <div className="flex items-center gap-2"><Select value={current} onValueChange={update}><SelectTrigger className="w-28"><SelectValue /></SelectTrigger><SelectContent>{options.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="icon" variant="outline" aria-label="回访备注"><MessageSquareText /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>回访备注</DialogTitle><DialogDescription>记录沟通进展、下一步和需要再次联系的事项。</DialogDescription></DialogHeader><div className="space-y-2"><Label htmlFor={`appointment-note-${id}`}>内部备注</Label><Textarea id={`appointment-note-${id}`} value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} className="min-h-32" />{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</div><DialogFooter><Button onClick={saveNote} disabled={saving}>{saving && <LoaderCircle className="animate-spin" />}保存备注</Button></DialogFooter></DialogContent></Dialog></div>; }
