"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, LoaderCircle, LockKeyhole, Mail, Sparkles } from "lucide-react";
import { MessageResponse } from "@/components/ai-elements/message";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Textarea } from "@/components/ui/textarea";
import { industries, sizeBands } from "@/lib/catalog";
import type { AssessmentRecommendation, RoiEstimate } from "@/lib/types";
import { trackPublicEvent } from "@/lib/analytics-client";

type Answers = { industry: string; size: string; business: string; repeatedWork: string; systems: string; volume: string; laborCost: string; budget: string; urgency: string; goal: string; followUp: string };
type Preview = { companyProfile: string; diagnosis: string; recommendations: AssessmentRecommendation[]; roi: RoiEstimate };
const initial: Answers = { industry: "", size: "", business: "", repeatedWork: "", systems: "", volume: "", laborCost: "", budget: "", urgency: "", goal: "", followUp: "" };

const steps = [
  { id: "profile", title: "先了解你的企业", description: "这些信息用来选择更接近的案例和行业基准。" },
  { id: "work", title: "找到最值得改造的工作", description: "请描述实际流程，不需要使用 AI 术语。" },
  { id: "baseline", title: "补充业务基线", description: "范围越清楚，ROI 区间越有参考价值。" },
  { id: "plan", title: "确认投入与目标", description: "我们会据此安排三阶段优先级。" },
] as const;

export function AssessmentWizard() {
  const router = useRouter(); const [step, setStep] = useState(0); const [answers, setAnswers] = useState(initial); const [followQuestion, setFollowQuestion] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [preview, setPreview] = useState<Preview | null>(null); const [email, setEmail] = useState(""); const [claiming, setClaiming] = useState(false);
  useEffect(() => { trackPublicEvent("assessment_started"); }, []);
  const update = (key: keyof Answers, value: string) => setAnswers((current) => ({ ...current, [key]: value }));
  function valid() { if (step === 0) return answers.industry && answers.size && answers.business.trim().length >= 2; if (step === 1) return answers.repeatedWork.trim().length >= 2 && answers.systems.trim().length >= 1; if (step === 2) return answers.volume.trim().length >= 1 && answers.laborCost.trim().length >= 1 && answers.followUp.trim().length >= 1; return answers.budget && answers.urgency && answers.goal.trim().length >= 2; }
  async function next() { setError(""); if (!valid()) { setError("请先完成本页的必要信息。"); return; } if (step === 1) { setLoading(true); const response = await fetch("/api/v1/assessments/follow-up", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(answers) }).catch(() => null); const data = response?.ok ? await response.json() : null; setFollowQuestion(data?.question ?? `针对“${answers.repeatedWork}”，每月大约处理多少次，一次需要多少时间？`); setLoading(false); } if (step < steps.length - 1) setStep((value) => value + 1); else await generate(); }
  async function generate() { setLoading(true); setError(""); const response = await fetch("/api/v1/assessments/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(answers) }).catch(() => null); const data = response ? await response.json().catch(() => null) : null; if (!response?.ok) { setError(data?.error ?? "核心建议生成失败，请稍后重试。"); setLoading(false); return; } setPreview(data.preview); trackPublicEvent("assessment_completed"); setLoading(false); }
  async function claim(event: React.FormEvent) { event.preventDefault(); setClaiming(true); setError(""); const response = await fetch("/api/v1/assessments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...answers, email }) }).catch(() => null); const data = response ? await response.json().catch(() => null) : null; if (!response?.ok) { setError(data?.error ?? "任务提交失败，请稍后重试。"); setClaiming(false); return; } trackPublicEvent("report_claimed"); router.push(`/assessment/status/${data.statusToken}/${data.reportToken}`); }

  if (preview) return <div className="mx-auto max-w-4xl"><div className="text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary text-primary-foreground"><CheckCircle2 /></span><p className="mt-5 text-xs font-semibold tracking-[0.16em] text-primary">初步体检完成</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">你的 AI 改造机会已经整理好</h1><p className="mt-3 text-sm text-muted-foreground">先查看规则引擎给出的核心判断，再提交生成 V4-Pro 深度报告。</p></div><Card className="mt-9 overflow-hidden py-0 shadow-none"><CardContent className="p-0"><div className="border-b bg-primary/[0.04] p-6 sm:p-8"><Badge variant="outline">{preview.companyProfile}</Badge><div className="mt-5"><MessageResponse>{preview.diagnosis}</MessageResponse></div></div><div className="grid gap-px bg-border md:grid-cols-3">{preview.recommendations.map((item) => <div key={item.stage} className="bg-card p-6"><p className="text-xs font-semibold text-primary">第 {item.stage} 阶段</p><h2 className="mt-2 font-semibold">{item.title}</h2><p className="mt-3 line-clamp-4 text-sm leading-6 text-muted-foreground">{item.reason}</p><div className="mt-5 text-xs text-muted-foreground">{item.timeline} · 难度{item.difficulty}</div></div>)}</div><div className="grid gap-6 p-6 sm:p-8 md:grid-cols-[1fr_1.1fr] md:items-center"><div><p className="text-xs text-muted-foreground">初步回收期</p><p className="mt-2 text-2xl font-semibold">{preview.roi.paybackPeriod}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{preview.roi.disclaimer}</p></div><form onSubmit={claim} className="rounded-xl border bg-muted/25 p-4"><Label htmlFor="report-email">邮箱接收完整报告通知</Label><div className="mt-2 flex gap-2"><div className="relative flex-1"><Mail className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input id="report-email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="pl-9" placeholder="name@company.com" /></div><Button type="submit" disabled={claiming}>{claiming ? <LoaderCircle className="animate-spin" /> : <LockKeyhole />}{claiming ? "提交中" : "深度生成"}</Button></div><p className="mt-2 text-[11px] leading-5 text-muted-foreground">V4-Pro 最高强度推理通常需要 1–3 分钟。提交后可关闭页面，完成时会发送私密报告链接。</p></form></div></CardContent></Card>{error && <p role="alert" className="mt-4 text-center text-sm text-destructive">{error}</p>}</div>;

  const optionClass = "flex cursor-pointer items-start gap-3 rounded-xl border bg-card p-4 transition-colors has-[[data-state=checked]]:border-primary has-[[data-state=checked]]:bg-primary/[0.045]";
  return <div className="mx-auto max-w-3xl"><div className="mb-8"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>第 {step + 1} / {steps.length} 步</span><span>{Math.round(((step + 1) / steps.length) * 100)}%</span></div><Progress value={((step + 1) / steps.length) * 100} className="mt-3 h-1.5" /></div><Card className="shadow-none"><CardContent className="p-6 sm:p-9"><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Sparkles className="size-5" /></span><div><h1 className="text-2xl font-semibold tracking-tight">{steps[step].title}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{steps[step].description}</p></div></div><div className="mt-8 space-y-7">
    {step === 0 && <><div className="space-y-3"><Label>你们主要属于哪个行业？</Label><RadioGroup value={answers.industry} onValueChange={(value) => update("industry", value)} className="grid sm:grid-cols-2">{industries.map((item) => <label key={item.id} className={optionClass}><RadioGroupItem value={item.displayName} /><span className="text-sm font-medium">{item.displayName}</span></label>)}</RadioGroup></div><div className="space-y-3"><Label>企业大约有多少人？</Label><RadioGroup value={answers.size} onValueChange={(value) => update("size", value)} className="grid sm:grid-cols-3">{sizeBands.slice(0, 6).map((item) => <label key={item} className={optionClass}><RadioGroupItem value={item} /><span className="text-sm">{item}</span></label>)}</RadioGroup></div><div className="space-y-2"><Label htmlFor="business">主要业务是什么？</Label><Textarea id="business" value={answers.business} onChange={(event) => update("business", event.target.value)} placeholder="例如：生产工业泵，主要服务国内设备制造商" /></div></>}
    {step === 1 && <><div className="space-y-2"><Label htmlFor="repeated">目前最耗时、最重复的工作是什么？</Label><Textarea id="repeated" value={answers.repeatedWork} onChange={(event) => update("repeatedWork", event.target.value)} className="min-h-28" placeholder="请描述谁在做、怎么做、哪里容易出错" /></div><div className="space-y-2"><Label htmlFor="systems">现在使用哪些系统或工具？</Label><Input id="systems" value={answers.systems} onChange={(event) => update("systems", event.target.value)} placeholder="例如：ERP、Excel、企业微信；没有可填“暂无”" /></div></>}
    {step === 2 && <><div className="rounded-xl border border-primary/20 bg-primary/[0.04] p-4"><div className="flex items-center gap-2 text-xs font-semibold text-primary"><Sparkles className="size-3.5" />动态追问</div><div className="mt-3 text-sm leading-7"><MessageResponse>{followQuestion}</MessageResponse></div><Textarea value={answers.followUp} onChange={(event) => update("followUp", event.target.value)} className="mt-3" placeholder="尽量提供数量、耗时和人数" /></div><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="volume">月业务量</Label><Input id="volume" value={answers.volume} onChange={(event) => update("volume", event.target.value)} placeholder="如：每月 3000 张单据" /></div><div className="space-y-2"><Label htmlFor="cost">相关人工成本</Label><Input id="cost" value={answers.laborCost} onChange={(event) => update("laborCost", event.target.value)} placeholder="如：4 人，每月约 3 万元" /></div></div></>}
    {step === 3 && <><div className="space-y-3"><Label>首阶段可接受的预算范围</Label><RadioGroup value={answers.budget} onValueChange={(value) => update("budget", value)} className="grid sm:grid-cols-2">{["3万元以内", "3–10万元", "10–30万元", "暂不确定"].map((item) => <label key={item} className={optionClass}><RadioGroupItem value={item} /><span className="text-sm">{item}</span></label>)}</RadioGroup></div><div className="space-y-3"><Label>希望多久开始见到结果？</Label><RadioGroup value={answers.urgency} onValueChange={(value) => update("urgency", value)} className="grid sm:grid-cols-3">{["1个月内", "3个月内", "半年内"].map((item) => <label key={item} className={optionClass}><RadioGroupItem value={item} /><span className="text-sm">{item}</span></label>)}</RadioGroup></div><div className="space-y-2"><Label htmlFor="goal">最希望改善哪个指标？</Label><Textarea id="goal" value={answers.goal} onChange={(event) => update("goal", event.target.value)} placeholder="例如：录单时间降低 50%，错误率控制在 1% 以内" /></div></>}
  </div>{error && <p role="alert" className="mt-5 text-sm text-destructive">{error}</p>}<div className="mt-9 flex items-center justify-between border-t pt-6"><Button variant="ghost" disabled={step === 0 || loading} onClick={() => setStep((value) => Math.max(0, value - 1))}><ArrowLeft />上一步</Button><Button size="lg" disabled={loading} onClick={next}>{loading ? <><LoaderCircle className="animate-spin" />{step === steps.length - 1 ? "正在整理核心建议" : "正在生成追问"}</> : <>{step === steps.length - 1 ? "查看核心建议" : "下一步"}<ArrowRight /></>}</Button></div></CardContent></Card><p className="mt-4 text-center text-[11px] leading-5 text-muted-foreground">问诊内容可能由配置的 AI 服务商处理。请勿填写商业秘密或未经授权的个人信息。</p></div>;
}
