"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { LoaderCircle, Save, Sparkles, Trash2 } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { industries, scenarios, businessFunctions, sizeBands } from "@/lib/catalog";
import type { CaseStudy } from "@/lib/types";

type Fields = Record<string, string>;
function EditorTextField({ id, label, area = false, placeholder, value, onChange }: { id: string; label: string; area?: boolean; placeholder?: string; value: string; onChange: (id: string, value: string) => void }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{area ? <Textarea id={id} value={value} onChange={(event) => onChange(id, event.target.value)} placeholder={placeholder} className="min-h-28" /> : <Input id={id} value={value} onChange={(event) => onChange(id, event.target.value)} placeholder={placeholder} />}</div>; }
function initialFields(item?: CaseStudy): Fields { return { version: String(item?.version ?? 1), slug: item?.slug ?? "", title: item?.title ?? "", organization: item?.organization.name ?? "", organizationSize: item?.organization.size ?? "未披露", industry: item?.industry.slug ?? "manufacturing", scenario: item?.scenarios[0]?.slug ?? "knowledge-base", businessFunction: item?.businessFunctions[0] ?? "经营管理", summary: item?.summary ?? "", background: item?.background ?? "", problem: item?.problem ?? "", solution: item?.solution ?? "", implementationSteps: item?.implementationSteps.join("\n") ?? "", duration: item?.duration ?? "未披露", cost: item?.cost ?? "未披露", roi: item?.roi ?? "未披露", results: item?.results.map((value) => `${value.label}：${value.value}`).join("\n") ?? "", risks: item?.risks ?? "", failureReason: item?.failureReason ?? "", outcomeStatus: item?.outcomeStatus ?? "undisclosed", confidence: item?.confidence ?? "pending", contentStatus: item?.contentStatus ?? "draft", sourceTitle: item?.sources[0]?.title ?? "", sourcePublisher: item?.sources[0]?.publisher ?? "", sourceUrl: item?.sources[0]?.url ?? "", sourcePublishedAt: item?.sources[0]?.publishedAt ?? "", sourceSupports: item?.sources[0]?.supports.join("\n") ?? "", editorComment: item?.editorComment.text ?? "", suitableFor: item?.editorComment.suitableFor ?? "", prerequisites: item?.editorComment.prerequisites ?? "" }; }
type StructureReview = { model: string; promptVersion: string; evidence: Array<{ field: string; quote: string; location: string }>; missingFields: string[]; conflicts: string[] };
export function CaseEditor({ item, readOnlyDemo = false }: { item?: CaseStudy; readOnlyDemo?: boolean }) { const router = useRouter(); const [fields, setFields] = useState(() => initialFields(item)); const [sourceText, setSourceText] = useState(""); const [saving, setSaving] = useState(false); const [structuring, setStructuring] = useState(false); const [structureReview, setStructureReview] = useState<StructureReview | null>(null); const [error, setError] = useState(""); const update = (key: string, value: string) => setFields((current) => ({ ...current, [key]: value }));
  async function structure() { setStructuring(true); setError(""); setStructureReview(null); const response = await fetch("/api/admin/structure", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sourceText }) }).catch(() => null); const data = response ? await response.json().catch(() => null) : null; if (!response?.ok) setError(data?.error ?? "结构化失败"); else { setFields((current) => { const next = { ...current }; for (const [key, value] of Object.entries(data.fields as Record<string, unknown>)) { if (!(key in current)) continue; next[key] = Array.isArray(value) ? value.map((entry) => typeof entry === "string" ? entry : `${(entry as { label?: string }).label ?? "结果"}：${(entry as { value?: string }).value ?? "未披露"}`).join("\n") : String(value ?? ""); } return next; }); setStructureReview({ model: data.model, promptVersion: data.promptVersion, evidence: data.fields.evidence ?? [], missingFields: data.fields.missingFields ?? [], conflicts: data.fields.conflicts ?? [] }); } setStructuring(false); }
  function payload() { const split = (value: string) => value.split(/\r?\n/).map((part) => part.trim()).filter(Boolean); return { ...fields, version: Number(fields.version) || 1, slug: fields.slug || undefined, implementationSteps: split(fields.implementationSteps), sourceSupports: split(fields.sourceSupports), results: split(fields.results).map((line) => { const [label, ...rest] = line.split(/[：:]/); const value = rest.join("：").trim() || "未披露"; return { label: label.trim(), value, kind: value.includes("未披露") ? "undisclosed" : "actual" }; }) }; }
  async function save() { setSaving(true); setError(""); const response = await fetch(item ? `/api/admin/cases/${item.id}` : "/api/admin/cases", { method: item ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload()) }).catch(() => null); const data = response ? await response.json().catch(() => null) : null; if (!response?.ok) { const details = Array.isArray(data?.issues) ? `：${data.issues.join("；")}` : ""; setError(`${data?.error ?? "保存失败"}${details}`); setSaving(false); return; } router.push("/admin/cases"); router.refresh(); }
  async function remove() { if (!item) return; setSaving(true); const response = await fetch(`/api/admin/cases/${item.id}`, { method: "DELETE" }); if (response.ok) { router.push("/admin/cases"); router.refresh(); } else { setError("删除失败"); setSaving(false); } }
  return <div className="space-y-6"><Card className="border-primary/20 bg-primary/[0.025] shadow-none"><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="size-5 text-primary" />DeepSeek 来源结构化</CardTitle></CardHeader><CardContent><Textarea value={sourceText} onChange={(event) => setSourceText(event.target.value)} className="min-h-40" placeholder="粘贴完整来源材料。模型只负责抽取与改写，未披露字段会保留为‘未披露’。" /><div className="mt-3 flex items-center justify-between gap-4"><p className="text-xs text-muted-foreground">使用 DeepSeek V4-Pro 最高推理强度，结果仍需人工核对。</p><Button type="button" variant="outline" onClick={structure} disabled={structuring || sourceText.trim().length < 30}>{structuring ? <LoaderCircle className="animate-spin" /> : <Sparkles />}AI 结构化</Button></div>{structureReview && <div className="mt-5 rounded-xl border bg-background p-4"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{structureReview.model}</Badge><Badge variant="secondary">{structureReview.promptVersion}</Badge><span className="text-xs text-muted-foreground">{structureReview.evidence.length} 条证据</span></div>{structureReview.missingFields.length > 0 && <p className="mt-3 text-xs leading-6 text-amber-800">未披露：{structureReview.missingFields.join("、")}</p>}{structureReview.conflicts.length > 0 && <p className="mt-2 text-xs leading-6 text-rose-700">来源冲突：{structureReview.conflicts.join("；")}</p>}<details className="mt-3"><summary className="cursor-pointer text-xs font-medium text-primary">查看字段证据</summary><div className="mt-3 max-h-64 space-y-2 overflow-auto">{structureReview.evidence.map((entry, index) => <div key={`${entry.field}-${index}`} className="rounded-lg bg-muted/60 p-3 text-xs leading-5"><p className="font-medium">{entry.field} · {entry.location}</p><p className="mt-1 text-muted-foreground">“{entry.quote}”</p></div>)}</div></details></div>}</CardContent></Card>
    {readOnlyDemo && <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">这是演示案例。配置 MongoDB 后可创建并保存正式案例。</p>}
    <Card className="shadow-none"><CardHeader><CardTitle>基本信息</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><EditorTextField id="title" label="案例标题 *" placeholder="" value={fields["title"] ?? ""} onChange={update} /></div><EditorTextField id="slug" label="URL Slug" placeholder="留空自动生成" value={fields["slug"] ?? ""} onChange={update} /><EditorTextField id="organization" label="企业主体 *" placeholder="" value={fields["organization"] ?? ""} onChange={update} /><div className="space-y-2"><Label>企业规模</Label><Select value={fields.organizationSize} onValueChange={(value) => update("organizationSize", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{sizeBands.map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>行业</Label><Select value={fields.industry} onValueChange={(value) => update("industry", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{industries.map((value) => <SelectItem key={value.id} value={value.slug}>{value.displayName}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>AI 场景</Label><Select value={fields.scenario} onValueChange={(value) => update("scenario", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{scenarios.map((value) => <SelectItem key={value.id} value={value.slug}>{value.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>业务部门</Label><Select value={fields.businessFunction} onValueChange={(value) => update("businessFunction", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{businessFunctions.map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="sm:col-span-2"><EditorTextField id="summary" label="一句话摘要 *" area placeholder="" value={fields["summary"] ?? ""} onChange={update} /></div></CardContent></Card>
    <Card className="shadow-none"><CardHeader><CardTitle>案例正文</CardTitle></CardHeader><CardContent className="grid gap-5"><EditorTextField id="background" label="业务背景 *" area placeholder="" value={fields["background"] ?? ""} onChange={update} /><EditorTextField id="problem" label="遇到的问题 *" area placeholder="" value={fields["problem"] ?? ""} onChange={update} /><EditorTextField id="solution" label="AI 解决方案 *" area placeholder="" value={fields["solution"] ?? ""} onChange={update} /><EditorTextField id="implementationSteps" label="实施步骤（每行一项）" area placeholder="" value={fields["implementationSteps"] ?? ""} onChange={update} /><div className="grid gap-5 sm:grid-cols-3"><EditorTextField id="duration" label="实施周期" placeholder="" value={fields["duration"] ?? ""} onChange={update} /><EditorTextField id="cost" label="投入成本" placeholder="" value={fields["cost"] ?? ""} onChange={update} /><EditorTextField id="roi" label="ROI" placeholder="" value={fields["roi"] ?? ""} onChange={update} /></div><EditorTextField id="results" label="效果指标（每行“指标：数值”）" area placeholder="" value={fields["results"] ?? ""} onChange={update} /><EditorTextField id="risks" label="风险与边界" area placeholder="" value={fields["risks"] ?? ""} onChange={update} />{fields.outcomeStatus === "failure" && <EditorTextField id="failureReason" label="失败原因与证据依据 *" area placeholder="必须能够由来源支持，不能仅依据 AI 判断" value={fields.failureReason ?? ""} onChange={update} />}</CardContent></Card>
    <Card className="shadow-none"><CardHeader><CardTitle>来源与编辑判断</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><EditorTextField id="sourceTitle" label="来源标题 *" placeholder="" value={fields["sourceTitle"] ?? ""} onChange={update} /><EditorTextField id="sourcePublisher" label="发布方 *" placeholder="" value={fields["sourcePublisher"] ?? ""} onChange={update} /><EditorTextField id="sourceUrl" label="原文 URL" placeholder="" value={fields["sourceUrl"] ?? ""} onChange={update} /><EditorTextField id="sourcePublishedAt" label="来源发布日期" placeholder="" value={fields["sourcePublishedAt"] ?? ""} onChange={update} /><div className="sm:col-span-2"><EditorTextField id="sourceSupports" label="来源支持的事实（每行一项）" area placeholder="" value={fields["sourceSupports"] ?? ""} onChange={update} /></div><div className="sm:col-span-2"><EditorTextField id="editorComment" label="编辑点评" area placeholder="" value={fields["editorComment"] ?? ""} onChange={update} /></div><EditorTextField id="suitableFor" label="适合" area placeholder="" value={fields["suitableFor"] ?? ""} onChange={update} /><EditorTextField id="prerequisites" label="前置条件" area placeholder="" value={fields["prerequisites"] ?? ""} onChange={update} /></CardContent></Card>
    <Card className="shadow-none"><CardHeader><CardTitle>审核与发布</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-3"><div className="space-y-2"><Label>项目结果</Label><Select value={fields.outcomeStatus} onValueChange={(value) => update("outcomeStatus", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="success">成功</SelectItem><SelectItem value="partial">部分达成</SelectItem><SelectItem value="failure">失败</SelectItem><SelectItem value="undisclosed">结果未披露</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>可信度</Label><Select value={fields.confidence} onValueChange={(value) => update("confidence", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="high">高</SelectItem><SelectItem value="medium">中</SelectItem><SelectItem value="pending">待核验</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>内容状态</Label><Select value={fields.contentStatus} onValueChange={(value) => update("contentStatus", value)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">草稿</SelectItem><SelectItem value="duplicate_review">重复复核</SelectItem><SelectItem value="in_review">内容审核</SelectItem><SelectItem value="published">发布</SelectItem><SelectItem value="rejected">退回</SelectItem><SelectItem value="archived">归档</SelectItem></SelectContent></Select></div></CardContent></Card>
    {error && <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="sticky bottom-4 flex items-center justify-between rounded-xl border bg-background/95 p-3 shadow-lg backdrop-blur"><div>{item && <AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" className="text-destructive" disabled={readOnlyDemo}><Trash2 />删除案例</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这个案例？</AlertDialogTitle><AlertDialogDescription>案例会被软删除并保留审计记录，不再出现在前台。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={remove}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div><Button size="lg" onClick={save} disabled={saving || readOnlyDemo}>{saving ? <LoaderCircle className="animate-spin" /> : <Save />}保存案例</Button></div>
  </div>;
}
