"use client";
import { useState } from "react";
import { AlertTriangle, CheckCircle2, LoaderCircle, ShieldAlert, Upload } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
type Result = { row: number; title?: string; status: string; score?: number; message?: string; error?: string; candidate?: { title: string; organization: string } };
const example = JSON.stringify([{ title: "某制造企业使用 OCR 自动录入订单", organization: "某制造企业", sourceUrl: "https://example.com/case-1?utm_source=demo", sourceTitle: "企业数字化案例", publishedAt: "2026-06-01", scenario: "OCR", department: "销售", solution: "识别订单并写入 ERP", result: "录入时间降低 60%", rawText: "来源材料全文可放在这里" }], null, 2);
export function ImportWorkbench() { const [format, setFormat] = useState<"json" | "csv">("json"); const [content, setContent] = useState(example); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [results, setResults] = useState<Result[]>([]); const [persisted, setPersisted] = useState(true); async function run() { setLoading(true); setError(""); const response = await fetch("/api/admin/imports", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ format, content }) }).catch(() => null); const data = response ? await response.json().catch(() => null) : null; if (!response?.ok) setError(data?.error ?? "预检失败"); else { setResults(data.results); setPersisted(data.persisted); } setLoading(false); } return <div><Card className="shadow-none"><CardContent className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">粘贴批量数据</h2><p className="mt-1 text-xs text-muted-foreground">单次最多 200 条；相同 URL 或内容哈希会保持幂等。</p></div><Select value={format} onValueChange={(value) => setFormat(value as "json" | "csv")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="json">JSON</SelectItem><SelectItem value="csv">CSV</SelectItem></SelectContent></Select></div><Textarea value={content} onChange={(event) => setContent(event.target.value)} className="mt-5 min-h-72 font-mono text-xs" spellCheck={false} /><div className="mt-4 flex items-center justify-between gap-4"><p className="text-xs leading-5 text-muted-foreground">必填：title、organization。推荐包含 sourceUrl、scenario、department、solution、result、rawText。</p><Button onClick={run} disabled={loading || !content.trim()}>{loading ? <LoaderCircle className="animate-spin" /> : <Upload />}开始去重预检</Button></div>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}</CardContent></Card>
    {results.length > 0 && <div className="mt-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">预检结果</h2>{!persisted && <Badge variant="secondary">演示预检 · 未写入数据库</Badge>}</div><div className="mt-4 space-y-3">{results.map((item) => { const high = item.status === "blocked_duplicate" || item.status === "exact_duplicate"; const medium = item.status === "needs_duplicate_review"; const Icon = high ? ShieldAlert : medium ? AlertTriangle : item.status === "invalid" ? AlertTriangle : CheckCircle2; return <Card key={item.row} className="py-0 shadow-none"><CardContent className="flex gap-4 p-4"><Icon className={`mt-0.5 size-5 shrink-0 ${high ? "text-rose-600" : medium ? "text-amber-600" : "text-primary"}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">第 {item.row} 行 · {item.title ?? "格式错误"}</p><Badge variant="outline">{item.status}</Badge>{typeof item.score === "number" && <Badge variant="secondary">相似度 {(item.score * 100).toFixed(1)}%</Badge>}</div><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.message || item.error || (item.candidate ? `最相似：${item.candidate.organization} / ${item.candidate.title}` : "未发现高相似案例，可进入暂存区")}</p></div></CardContent></Card>; })}</div></div>}
  </div>; }
