# -*- coding: utf-8 -*-
"""从《2024中国大模型先锋案例TOP30》（沙丘社区）提取 30 个企业 AI 落地案例，生成完整 CaseStudy JSON。

源文本：report_ocr/2024中国大模型先锋案例TOP30.txt
入库：node scripts/insert-cases.mjs cases_json/gen_top30_2024_cases.json
"""
import json
import os
import re
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "cases_json", "gen_top30_2024_cases.json")

# ---------- 完整 catalog 对象（shape 与 gen_research_cases.py 一致，已跑通） ----------
INDUSTRIES = {
    "manufacturing": {"id": "manufacturing", "code": "C", "name": "制造业", "displayName": "制造业",
                      "slug": "manufacturing", "description": "生产、质检、设备维护、供应链与经营管理中的 AI 实践。",
                      "icon": "factory", "featured": True, "standardVersion": "v2026.07"},
    "retail": {"id": "retail", "code": "F52", "name": "零售业", "displayName": "零售与消费",
               "slug": "retail", "description": "选品、库存、门店运营、客服与会员营销案例。",
               "icon": "shopping-bag", "featured": True, "standardVersion": "v2026.07"},
    "logistics": {"id": "logistics", "code": "G", "name": "交通运输、仓储和邮政业", "displayName": "物流与仓储",
                  "slug": "logistics", "description": "订单、仓储、路径、调度和运力管理案例。",
                  "icon": "truck", "featured": True, "standardVersion": "v2026.07"},
    "finance": {"id": "finance", "code": "J", "name": "金融业", "displayName": "金融",
                "slug": "finance", "description": "风控、合规、运营与知识服务案例。",
                "icon": "landmark", "featured": True, "standardVersion": "v2026.07"},
    "healthcare": {"id": "healthcare", "code": "Q84", "name": "卫生", "displayName": "医疗健康",
                   "slug": "healthcare", "description": "病历、随访、辅助诊疗和医院运营案例。",
                   "icon": "heart-pulse", "featured": True, "standardVersion": "v2026.07"},
    "education": {"id": "education", "code": "P", "name": "教育", "displayName": "教育",
                  "slug": "education", "description": "教学内容、教务、知识问答和学习支持案例。",
                  "icon": "graduation-cap", "featured": True, "standardVersion": "v2026.07"},
    "software-internet": {"id": "software-internet", "code": "I65", "name": "软件和信息技术服务业", "displayName": "软件与互联网",
                          "slug": "software-internet", "description": "研发、运维、客服、销售与内容生产案例。",
                          "icon": "code", "featured": True, "standardVersion": "v2026.07"},
    "energy-mining": {"id": "energy-mining", "code": "B", "name": "采矿业", "displayName": "能源与矿山",
                      "slug": "energy-mining", "description": "煤矿、油气、电力与矿山的智能化、安全管控与生产经营 AI 实践。",
                      "icon": "fuel", "featured": True, "standardVersion": "v2026.07"},
    "automotive": {"id": "automotive", "code": "C36", "name": "汽车制造业", "displayName": "汽车",
                   "slug": "automotive", "description": "整车与零部件研发、制造、营销、客服与智能座舱案例。",
                   "icon": "car", "featured": True, "standardVersion": "v2026.07"},
    "telecom": {"id": "telecom", "code": "I63", "name": "电信、广播电视和卫星传输服务", "displayName": "通信",
                "slug": "telecom", "description": "网络运维、客服、营销与算力调度的 AI 实践。",
                "icon": "radio-tower", "featured": False, "standardVersion": "v2026.07"},
    "government": {"id": "government", "code": "S", "name": "公共管理、社会保障和社会组织", "displayName": "政务与公共服务",
                   "slug": "government", "description": "政务热线、政策问答、城市治理与公共服务的 AI 应用。",
                   "icon": "building-2", "featured": False, "standardVersion": "v2026.07"},
}
SCENARIOS = {
    "ocr": {"id": "ocr", "name": "OCR / 文档识别", "slug": "ocr",
            "description": "从票据、合同、单据和图片提取结构化信息。", "synonyms": ["文字识别", "文档识别", "录单"],
            "icon": "scan-text", "featured": True},
    "customer-service": {"id": "customer-service", "name": "智能客服", "slug": "customer-service",
                         "description": "面向客户或员工的智能问答与工单辅助。", "synonyms": ["AI客服", "客服机器人", "在线客服"],
                         "icon": "messages-square", "featured": True},
    "knowledge-base": {"id": "knowledge-base", "name": "企业知识库", "slug": "knowledge-base",
                       "description": "让制度、产品和业务资料可检索、可问答。", "synonyms": ["知识问答", "RAG", "内部知识库"],
                       "icon": "library-big", "featured": True},
    "sales": {"id": "sales", "name": "销售辅助", "slug": "sales",
              "description": "线索分析、销售跟进、沟通总结和方案生成。", "synonyms": ["销售助手", "商机分析", "销售Agent"],
              "icon": "trending-up", "featured": True},
    "quotation": {"id": "quotation", "name": "智能报价", "slug": "quotation",
                  "description": "根据产品、物料和规则辅助快速、准确报价。", "synonyms": ["报价Agent", "自动报价", "报价"],
                  "icon": "receipt-text", "featured": True},
    "workflow": {"id": "workflow", "name": "流程自动化", "slug": "workflow",
                 "description": "连接业务系统，减少重复录入和人工流转。", "synonyms": ["Workflow", "RPA", "自动化流程"],
                 "icon": "workflow", "featured": True},
    "quality-inspection": {"id": "quality-inspection", "name": "智能质检", "slug": "quality-inspection",
                           "description": "视觉、语音或文本质量检查和异常识别。", "synonyms": ["视觉质检", "AI质检"],
                           "icon": "scan-search", "featured": True},
    "forecast": {"id": "forecast", "name": "预测与分析", "slug": "forecast",
                 "description": "需求、销量、库存、设备和经营指标预测。", "synonyms": ["需求预测", "数据分析", "预测性维护"],
                 "icon": "chart-no-axes-combined", "featured": False},
    "content-generation": {"id": "content-generation", "name": "内容生成", "slug": "content-generation",
                           "description": "营销、商品、培训和多语言内容生产。", "synonyms": ["AIGC", "营销文案", "内容创作"],
                           "icon": "sparkles", "featured": False},
    "agent": {"id": "agent", "name": "Agent", "slug": "agent",
              "description": "能够规划、调用工具并执行多步任务的 AI 助手。", "synonyms": ["智能体", "AI Agent"],
              "icon": "bot", "featured": True},
    "production-scheduling": {"id": "production-scheduling", "name": "智能排产与工艺优化", "slug": "production-scheduling",
                              "description": "生产计划、排程与工艺参数优化。", "synonyms": ["排产", "工艺优化", "生产调度"],
                              "icon": "gauge", "featured": False},
    "ops-inspection": {"id": "ops-inspection", "name": "智能运维与巡检", "slug": "ops-inspection",
                       "description": "设备运维、远程巡检与异常预警。", "synonyms": ["运维", "巡检", "预测性维护"],
                       "icon": "wrench", "featured": False},
    "rnd-design": {"id": "rnd-design", "name": "研发设计与仿真", "slug": "rnd-design",
                   "description": "研发设计、仿真与实验辅助。", "synonyms": ["研发", "仿真", "设计辅助"],
                   "icon": "flask-conical", "featured": False},
    "ai-infra": {"id": "ai-infra", "name": "算力基础设施与AI平台", "slug": "ai-infra",
                 "description": "算力调度、AI 平台与基础设施。", "synonyms": ["算力", "AI平台", "基础设施"],
                 "icon": "cpu", "featured": False},
}
BUSINESS_FUNCTIONS = {"战略与运营", "财务与融资", "市场与销售", "客户成功", "供应链/物流",
                      "研发与设计", "生产制造", "人力资源", "法务与合规", "信息技术"}
VALID_OUTCOME = {"success", "partial", "failure", "undisclosed"}
VALID_CONF = {"high", "medium", "pending"}


def slugify(title):
    s = re.sub(r"[^\w\u4e00-\u9fff]+", "-", title).strip("-").lower()
    return s[:80]


def dedup_vector(text):
    vec = [0.0] * 40
    for ch in text:
        vec[ord(ch) % 40] += 1.0
    norm = sum(v * v for v in vec) ** 0.5 or 1.0
    return [round(v / norm, 4) for v in vec]


def build(case):
    ind = INDUSTRIES[case["industry"]]
    scns = [SCENARIOS[s] for s in case["scenarios"]]
    assert case["industry"] in INDUSTRIES, f"unknown industry {case['industry']}"
    for s in case["scenarios"]:
        assert s in SCENARIOS, f"unknown scenario {s}"
    for b in case["businessFunctions"]:
        assert b in BUSINESS_FUNCTIONS, f"unknown businessFunction {b}"
    assert case["outcomeStatus"] in VALID_OUTCOME
    assert case["confidence"] in VALID_CONF

    full = case["title"]
    slug = case.get("slug") or slugify(full)
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    record = {
        "id": case.get("id") or f"case-{slug}",
        "version": 1,
        "slug": slug,
        "title": full,
        "organization": case["organization"],
        "industry": ind,
        "scenarios": scns,
        "businessFunctions": case["businessFunctions"],
        "summary": case["summary"],
        "background": case["background"],
        "problem": case["problem"],
        "solution": case["solution"],
        "implementationSteps": case["implementationSteps"],
        "duration": case["duration"],
        "cost": case["cost"],
        "results": case["results"],
        "roi": case["roi"],
        "risks": case["risks"],
        "editorComment": case["editorComment"],
        "implementers": case["implementers"],
        "outcomeStatus": case["outcomeStatus"],
        "contentStatus": "published",
        "confidence": case["confidence"],
        "sources": case["sources"],
        "featured": case["featured"],
        "views": 0,
        "dedupVector": dedup_vector(full),
        "publishedAt": case["publishedAt"],
        "updatedAt": now,
        "implementationYear": case.get("implementationYear"),
        "implementationTimePrecision": case.get("implementationTimePrecision", "month"),
        "techPath": case.get("techPath", []),
        "modelStack": case.get("modelStack", []),
        "sourceReport": case.get("sourceReport"),
        "tags": case.get("tags", []),
        "seo": case.get("seo", {}),
    }
    return record


SRC = {
    "id": "src-top30-2024",
    "title": "2024中国大模型先锋案例TOP30",
    "publisher": "沙丘社区",
    "type": "institution",
    "url": "https://www.shaqiu.cn",
    "publishedAt": "2024-01-20",
    "collectedAt": "2026-07-23",
    "accessibility": "available",
    "supports": ["summary", "solution", "results", "roi"],
}
SR = {"title": "2024中国大模型先锋案例TOP30", "publisher": "沙丘社区", "year": 2024}
PUB = "2024-01-20"
YEAR = 2023


def mk(slug, title, org, ind, scns, bf, summary, background, problem, solution, steps,
       results, roi, tech, models, tags, featured=False):
    return {
        "id": f"case-{slug}", "slug": f"case-{slug}", "title": title, "organization": org,
        "industry": ind, "scenarios": scns, "businessFunctions": bf, "summary": summary,
        "background": background, "problem": problem, "solution": solution,
        "implementationSteps": steps, "duration": "持续迭代（2023年落地）", "cost": "未披露",
        "results": results, "roi": roi,
        "risks": "大模型存在幻觉与合规风险，需结合知识库与人工复核；行业数据的安全与隐私保护要求高；垂直场景的模型微调与效果持续调优成本不低。",
        "editorComment": {
            "suitableFor": "与案例方同行业、有相似业务痛点的企业",
            "prerequisites": "具备较完整的信息化与数据基础；有明确的高价值落地场景；有推动 AI 落地的组织意愿",
            "priority": "条件具备后开展",
            "text": f"{org['name']}的实践入选沙丘社区《2024中国大模型先锋案例TOP30》，在{ind}领域具备示范意义，建议同行业企业参考其落地路径。",
        },
        "implementers": [{"name": f"{org['name']}（联合技术供应商）", "role": "其他"}],
        "outcomeStatus": "success", "confidence": "high",
        "sources": [dict(SRC)], "featured": featured,
        "publishedAt": PUB, "implementationYear": YEAR, "implementationTimePrecision": "month",
        "techPath": tech, "modelStack": models, "sourceReport": dict(SR), "tags": tags, "seo": {
            "metaTitle": f"{title} - 大模型先锋案例",
            "metaDescription": summary[:80],
            "keywords": tags,
        },
    }


CASES = [
    mk("top30-boehringer-rag", "勃林格殷格翰：基于RAG的医学资料检索增强（勃小智）",
       {"id": "org-boehringer", "name": "勃林格殷格翰", "size": "large", "region": "德国/中国", "type": "foreign"},
       "healthcare", ["knowledge-base"], ["研发与设计", "市场与销售"],
       "勃林格殷格翰面向医药代表提供 Chatbot 智能问答，并基于大模型与知识图谱实现医学内容生产自动化，解决医学问询的时效性与合规性问题，提升学术推广效率。",
       "勃林格殷格翰为跨国制药企业，医药代表需高频回答医生关于医学与产品平台的问询，传统 FAQ 人工生成+合规审核周期长、内容更新慢。",
       "医学问询时效性与合规性要求高，人工维护 FAQ 难以及时更新，回答准确性与满意度受限。",
       "在 Chatbot 基础上引入大模型与知识图谱，通过向量检索匹配问题与知识库相似度，自动生成并审核医学内容，给出客观科学依据，提升内容生产自动化与回答精准度。",
       ["搭建医学 Chatbot 智能问答", "融合大模型与知识图谱做内容生产自动化", "向量检索+相似度匹配知识库", "输出客观科学依据、提升满意度"],
       [{"label": "内容更新时效", "value": "大幅提升", "kind": "actual"}],
       "基于大模型与知识图谱实现医学内容生产自动化，显著提升素材更新时效与回答准确率、满意度。",
       ["大模型", "知识图谱", "RAG"], ["未披露（自研+知识图谱）"],
       ["医疗", "RAG", "知识库", "医药"], featured=False),

    mk("top30-bazhua-kyligence", "八爪网络：基于对话式AI指标分析的猎头管理与决策洞察",
       {"id": "org-bazhua", "name": "八爪网络（猎必得）", "size": "medium", "region": "中国", "type": "private"},
       "software-internet", ["forecast", "agent"], ["信息技术", "市场与销售"],
       "猎必得采用 Kyligence Zen 指标平台与 Kyligence Copilot 数智助理，简化数据分析与管理流程，提供猎头效率指标与漏斗分析，提升整体猎头服务效率与质量。",
       "八爪网络旗下猎必得为招聘平台，猎头与运营人员需自助分析海量招聘数据，传统 BI 门槛高、效率低。",
       "猎头群体管理依赖经验，缺乏数据驱动的效率指标与漏斗分析，招聘效率与求职体验难以优化。",
       "引入智能一站式指标平台与 AI 数智助理，融合 AI 数据分析与大模型能力，提供自助式分析与决策洞察，帮助理解市场需求、个性化职业建议。",
       ["部署 Kyligence Zen 指标平台", "接入 Kyligence Copilot 数智助理", "构建猎头效率指标与漏斗分析", "自助式数据驱动决策"],
       [{"label": "猎头管理效率", "value": "优化提升", "kind": "actual"}],
       "通过 AI 增强的指标引擎与数智助理，实现数据驱动决策，提升招聘效率与求职体验。",
       ["大模型", "数据分析", "指标平台"], ["Kyligence Zen", "Kyligence Copilot"],
       ["招聘", "数据分析", "智能体"], featured=False),

    mk("top30-orient-zxnt", "东方资管：东方红智能小牛 AI 投研助理平台",
       {"id": "org-orient", "name": "东方证券资产管理有限公司", "size": "large", "region": "中国", "type": "soe"},
       "finance", ["forecast", "agent"], ["财务与融资", "研发与设计"],
       "东证资管联合东方证券开发基于大模型的 AI 投研助理「东方红智能小牛」，以问答方式提供金融辅助服务，在路演速读、智能风控、债券询价交易、问制度等场景展开应用。",
       "东方红资管为头部券商资管，投研人员每日面对海量金融信息，难以快速精准获取有价值内容。",
       "基金经理与研究员信息过载，投研知识问答与决策辅助是大模型最具业务价值的探索方向之一。",
       "构建大模型驱动的投研助理平台，通过问答交互提供路演速读、智能风控、债券询价、制度问答等定制化能力，让投研人员聚焦核心任务。",
       ["联合开发东方红智能小牛", "路演速读与智能风控", "债券询价交易辅助", "问制度等问答场景"],
       [{"label": "信息获取效率", "value": "快速精准", "kind": "actual"}],
       "协助提升投资经理管理大规模资金能力，扩大资产管理边界，向 AI 赋能增效每位员工的目标看齐。",
       ["大模型", "智能体", "金融NLP"], ["未披露基座大模型"],
       ["金融", "投研", "智能体"], featured=False),

    mk("top30-gf-sec-verify", "广发证券：基于金融大模型的智能化核查项目",
       {"id": "org-gfsec", "name": "广发证券", "size": "large", "region": "中国", "type": "soe"},
       "finance", ["workflow", "agent"], ["财务与融资", "信息技术"],
       "广发证券联合文因互联运用金融大模型建设语料、提示、质控工程，落地文档智能抽取、智能生成、智能核查三大场景，打造投行文档抽取/生成/核查一体化方案。",
       "广发证券投行业务产生大量底稿与非结构化文档，数据分散、难以提取汇总。",
       "投行文档标准化产出依赖人工，效率低、风险高；底稿数据分散无法有效归集。",
       "建设金融大模型应用基础架构（语料/提示/质控工程），打通文档智能抽取、智能生成、智能核查三大场景，实现一体化解决方案与数据自动归集、结构化存储。",
       ["建设语料/提示/质控工程", "文档智能抽取", "智能生成与智能核查", "数据自动归集结构化"],
       [{"label": "文档产出效率", "value": "提升、风险降低", "kind": "actual"}],
       "赋能投行业务文档生成与标准化，提升效率与质量、降低业务风险；实体抽取补充数据自动归集空白。",
       ["大模型", "文档抽取", "工作流"], ["文因互联金融大模型"],
       ["金融", "投行", "文档抽取"], featured=False),

    mk("top30-sgcc-knowledge", "国家电网：基于电力认知大模型的设备运检知识助手",
       {"id": "org-sgcc", "name": "国家电网", "size": "extraLarge", "region": "中国", "type": "soe"},
       "energy-mining", ["knowledge-base", "ops-inspection"], ["生产制造", "信息技术"],
       "国家电网联合百度，基于海量电力样本与运检经验，结合文心大模型与知识图谱，开发电力认知大模型设备运检知识助手，实现知识便捷查询、快速学习与作业辅助。",
       "国家电网智能电网研究院拥有海量高质量电力样本与运检场景 AI 研发经验，设备运检环节知识管理需求强。",
       "电力设备运检资料分散、标准繁多，一线人员难以快速精准检索与问答，影响运维智能化水平。",
       "基于电力认知大模型，融合文心系列大模型、深度学习与知识图谱增强，构建设备运检知识助手，赋能知识服务与计算引擎，支撑资料管理、标准检索、智能问答与移动应用。",
       ["构建电力认知大模型", "设备资料在线管理", "技术标准智能问答", "移动应用与运维检修场景"],
       [{"label": "运检智能化水平", "value": "显著提高", "kind": "actual"}],
       "推动电网运营精细化、自动化、智能化，提高电力设备运检智能化水平，为电力行业数字化转型提供参考。",
       ["大模型", "知识图谱", "电力认知"], ["百度文心大模型"],
       ["能源", "电力", "知识库", "运维"], featured=False),

    mk("top30-guojin-codes", "国金证券：基于aixcoder代码大模型的智能化软件开发",
       {"id": "org-guojin", "name": "国金证券", "size": "large", "region": "中国", "type": "soe"},
       "finance", ["rnd-design"], ["信息技术", "研发与设计"],
       "国金证券以 aixcoder 代码大模型为核心，结合三十年金融软件资产与 AI 生态，构建代码大模型工程化应用框架，实现开发效率平均提升30%、单元测试覆盖率提升20%。",
       "国金证券沉淀三十年金融行业软件资产，软件开发体量庞大，对编码效率与测试覆盖有刚性需求。",
       "证券行业软件工程领域特定上下文复杂，通用代码模型难以贴合实际项目逻辑。",
       "以 aixcoder 代码大模型为核心引擎，融合领域数据集与专家知识，构建工程化应用框架，覆盖编码、测试、搜索等环节，实现代码/设计/系统自动化。",
       ["引入 aixcoder 代码大模型", "融合领域数据集与专家知识", "构建工程化框架", "覆盖编码/测试/搜索"],
       [{"label": "开发效率", "value": "平均提升30%", "improvement": "+30%", "kind": "actual"},
        {"label": "单元测试覆盖率", "value": "提升20%", "improvement": "+20%", "kind": "actual"}],
       "结合领域知识让代码更规范、更贴合项目逻辑，可广泛应用于编码、测试、搜索，实现代码/设计/系统自动化。",
       ["代码大模型", "软件工程"], ["aixcoder 代码大模型"],
       ["金融", "代码大模型", "研发"], featured=False),

    mk("top30-hubei-exam-agent", "湖北市场监管宣教中心：AI 组卷判卷 Agent",
       {"id": "org-hubei", "name": "湖北省市场管理监督局宣教中心", "size": "medium", "region": "湖北", "type": "government"},
       "education", ["agent", "content-generation"], ["人力资源", "信息技术"],
       "湖北市场监管宣教中心联合澜码科技，基于企业级 AI Agent 平台 AskXBOT 研发「AI组卷判卷」Agent：依据文档/题型模板快速组卷，并为老师提供智能判卷。",
       "湖北省市场管理监督局宣教中心承担培训考试，传统组卷与判卷耗费大量人力，且难以个性化。",
       "培训考试组卷慢、判卷人力不足，难以普惠与个性化教学。",
       "基于澜码 AskXBOT 平台构建组卷与判卷双 Agent：组卷 Agent 按资料/题型/数量快速组合试卷，判卷 Agent 智能批改并赋能培训考试。",
       ["部署澜码 AskXBOT 平台", "研发 AI 组卷 Agent", "研发 AI 判卷 Agent", "赋能培训考试"],
       [{"label": "应用复制性", "value": "国内首创、可广泛复制", "kind": "actual"}],
       "组卷判卷 Agent 属国内首创且可广泛复制于教育行业，有望实现“普惠教育”，弥补人力不足与学生差异性。",
       ["智能体", "内容生成"], ["澜码 AskXBOT"],
       ["教育", "智能体", "组卷判卷"], featured=False),

    mk("top30-haimeng-supply", "海盟控股：基于供应链大模型的数字员工",
       {"id": "org-haimeng", "name": "海盟控股", "size": "medium", "region": "中国", "type": "private"},
       "logistics", ["agent", "workflow"], ["供应链/物流", "客户成功"],
       "海盟控股基于供应链大模型的数字员工超自动化平台，以自然语言对话打造虚拟数字员工专家团队（运价经理、物流追踪、行业案例等），协助白领完成数字化工作。",
       "海盟控股为跨境供应链企业，白领员工承担大量运价、追踪、翻译、问答等重复性工作。",
       "供应链业务沟通与执行高度依赖人工，端到端（营销-履约-财务）全局自动化程度低。",
       "基于供应链大模型构建壹咨数字员工超自动化平台，提供开箱即用 Agent 与精准行业答案，实现从图形交互到自然语言交互的范式转变，端到端全局超自动化。",
       ["构建供应链大模型平台", "打造数字员工专家团队", "自然语言式交互", "端到端超自动化"],
       [{"label": "交互范式", "value": "图形→自然语言", "kind": "actual"}],
       "颠覆 SaaS 既有交互范式，提供个性智能化供应链服务，赋能业务模式变革与提效、生产力跃迁。",
       ["大模型", "智能体", "工作流"], ["壹咨供应链大模型"],
       ["供应链", "数字员工", "智能体"], featured=False),

    mk("top30-geely-xingrui", "吉利汽车：星睿 AI 大模型全栈自研",
       {"id": "org-geely", "name": "吉利汽车", "size": "large", "region": "中国", "type": "private"},
       "automotive", ["agent", "knowledge-base"], ["研发与设计", "生产制造"],
       "吉利星睿 AI 大模型是吉利全栈自研的汽车行业全场景大模型，打通研发、制造等造车全链路，并发布 WoW 壁纸、AI 绘本等多款 AI 原生应用。",
       "吉利汽车为头部自主车企，在芯片、算法、平台、应用多层面布局 AI 全栈自研。",
       "汽车行业垂直领域知识复杂，需自主可控的 AI 能力支撑研发制造与用户体验。",
       "全栈自研星睿 AI 大模型，构建完整 AI 生态，打通研发/制造全链路，并落地 AI 原生应用（WoW 壁纸、AI 绘本）搭载于智能电动产品。",
       ["全栈自研星睿大模型", "打通研发制造全链路", "发布 AI 原生应用", "搭载智能电动产品"],
       [{"label": "研发制造效能", "value": "全面提升", "kind": "actual"}],
       "实现 AI 技术自主控制与持续优化，提升研发制造效能与市场竞争力，提供智能化个性化出行体验。",
       ["大模型", "智能体", "知识库"], ["吉利星睿 AI 大模型（自研）"],
       ["汽车", "全栈自研", "大模型"], featured=False),

    mk("top30-jinan-police", "济南市中公安：面向网格现代化治理的 AI 大模型应用",
       {"id": "org-jinan", "name": "济南市中公安分局", "size": "large", "region": "济南", "type": "government"},
       "government", ["agent", "knowledge-base"], ["战略与运营", "客户成功"],
       "济南市公安局中区分局「卫民小微」警务微信平台利用微信与 AI，提供警民直连、AI 智能回复、信息采集、扁平化管理、个性化宣防五大功能，构建在线政务一体化。",
       "济南市中公安需以简便权威渠道服务广大群众，政策文档多样、基层治理触点广。",
       "基层治理需线上常态化落实便民、纠纷上报、反诈宣防，传统方式难触达“最后一公里”。",
       "基于大模型加工政策文档为本地知识库，按交流内容精准适配最新政策，提供全天候智能政务服务，线上网格化落实便民/纠纷/反诈等公共治理。",
       ["搭建卫民小微警务微信平台", "政策文档本地知识库", "AI 智能回复与宣防", "网格化基层治理"],
       [{"label": "服务触达", "value": "延伸至基层最后一公里", "kind": "actual"}],
       "实现与居民无感链接与深度触达，快速查政策、查证件，常态化落实便民/纠纷/反诈等公共治理。",
       ["大模型", "智能体", "知识库"], ["未披露基座大模型"],
       ["政务", "基层治理", "智能体"], featured=False),

    mk("top30-leihuo-art", "网易雷火：丹青大模型助力游戏美术生产",
       {"id": "org-leihuo", "name": "网易雷火游戏", "size": "large", "region": "中国", "type": "private"},
       "software-internet", ["content-generation"], ["研发与设计", "生产制造"],
       "网易伏羲基于雷火多年美术资产，自研多款游戏美术大模型并搭建在线 AI 生图平台，融入美术生产管线，在保质量前提下实现降本增效。",
       "网易雷火积累大量游戏美术资产，美术生产是游戏研发的成本与产能瓶颈。",
       "传统人工制作美术资产成本高、周期长，难以满足多项目并行需求。",
       "针对不同项目风格自研美术大模型，搭建可在线使用的 AI 生图平台融入生产管线，坚持“人机协作”而非直接使用 AI 结果，形成模型训练与管线搭建服务标准。",
       ["自研多款游戏美术大模型", "搭建在线 AI 生图平台", "融入美术生产管线", "沉淀训练/管线标准"],
       [{"label": "总体生产", "value": "大幅提效", "kind": "actual"}],
       "在保质量前提下实现降本增效，并通过服务标准快速将 AI 生图能力迁移到各项目。",
       ["AIGC", "图像生成"], ["丹青/伏羲美术大模型（自研）"],
       ["游戏", "美术", "AIGC"], featured=False),

    mk("top30-noah-kb", "诺亚财富：基于领域大模型的智能知识库与知识助手",
       {"id": "org-noah", "name": "诺亚财富", "size": "large", "region": "中国", "type": "private"},
       "finance", ["knowledge-base"], ["客户成功", "信息技术"],
       "诺亚财富基于中关村科金金融大模型与智能客服技术打造智能知识库，以知识助手形式为员工与用户提供基于企业文档的智能问答，大幅提升意图识别与回复准确率。",
       "诺亚财富为财富管理企业，客服系统问答量大，需低成本、高准确的知识问答服务。",
       "传统客服知识管理成本高，问答意图识别与回复准确率不足。",
       "基于自研金融大模型与智能客服构建智能知识库，支持多模态文档分析、QA 自动抽取、知识自动标签化，推进知识管理新范式。",
       ["构建金融大模型智能知识库", "多模态文档分析", "QA 问答对自动抽取", "知识自动标签化"],
       [{"label": "问答意图/回复准确率", "value": "大幅提升", "kind": "actual"}],
       "单卡推理、单周迭代实现低成本模型微调，推动更智能、更低成本的知识问答服务。",
       ["大模型", "知识库", "智能客服"], ["中关村科金金融大模型"],
       ["金融", "知识库", "智能客服"], featured=False),

    mk("top30-aispeech-office", "思必驰：DFM-2 大模型在智慧办公场景的应用",
       {"id": "org-aispeech", "name": "思必驰", "size": "medium", "region": "中国", "type": "private"},
       "software-internet", ["workflow", "content-generation"], ["信息技术", "客户成功"],
       "思必驰将 DFM-2 大模型与办公软硬件深度结合：软件支持 AI 摘要、待办、语篇规整、一键成稿；硬件升级为本地+远程双向降噪与 AI 追踪。",
       "思必驰为智能语音企业，办公产品需在会议、文档等场景提升用户效率。",
       "传统办公软件整理会议纪要与降噪能力弱，远程沟通效率低。",
       "将 DFM-2 大模型能力融入办公软件与硬件：AI 摘要/一键成稿/语篇规整，硬件由单向降噪升级为本地+远程双向降噪并支持 AI 追踪。",
       ["DFM-2 融入办公软件", "AI 摘要/一键成稿", "硬件双向降噪", "AI 追踪模式"],
       [{"label": "出稿效率", "value": "开会1小时→出稿5分钟", "kind": "actual"}],
       "从“开会1小时整理3小时”到“开会1小时出稿5分钟”，办公效率显著提升，远程沟通听得清、看得见。",
       ["大模型", "工作流", "内容生成"], ["思必驰 DFM-2 大模型"],
       ["办公", "会议", "内容生成"], featured=False),

    mk("top30-sdenergy-mine", "山东能源集团：基于盘古大模型的智能矿山",
       {"id": "org-sdenergy", "name": "山东能源集团", "size": "extraLarge", "region": "中国", "type": "soe"},
       "energy-mining", ["ops-inspection", "production-scheduling"], ["生产制造", "信息技术"],
       "山东能源集团基于盘古矿山大模型构建「1+4+N」体系（1个AI平台+4个能力+N个场景），将算法模型流水化应用到不同业务，已在9大业务系统、40+场景、8个矿井规模使用。",
       "山东能源集团为大型煤炭企业，采掘机运通洗选等环节多、场景复杂。",
       "传统 AI 方案泛化性差、难以大规模复制，煤炭行业需从小模型向大模型演进。",
       "基于盘古矿山大模型构建「1+4+N」体系，以可复用算法模型流水化应用，减少专家干预与调优，实现快速复制推广。",
       ["构建 1+4+N 体系", "盘古矿山大模型", "9 大业务系统落地", "8 个矿井规模使用"],
       [{"label": "落地矿井", "value": "全国8个", "kind": "actual"},
        {"label": "业务场景", "value": "9大系统40+场景", "kind": "actual"}],
       "解决传统 AI 泛化差、难复制问题，从小模型到大模型是煤炭行业必然方向，实现快速复制推广。",
       ["大模型", "智能运维", "排产"], ["华为盘古矿山大模型"],
       ["能源", "矿山", "智能运维"], featured=False),

    mk("top30-saic-qa", "上汽乘用车：基于AI大模型的汽车在线问答平台",
       {"id": "org-saic", "name": "上汽乘用车", "size": "large", "region": "中国", "type": "soe"},
       "automotive", ["knowledge-base"], ["研发与设计", "客户成功"],
       "上汽乘用车基于鼎捷雅典娜 ChatFile 搭建汽车在线问答平台，针对 PDF/WORD/PPT/EXCEL 等非结构化文档实现自然语言交互，应用于研发、内部运维、售后等场景。",
       "上汽乘用车内部沉淀大量非结构化企业知识文档，员工查找与学习成本高。",
       "企业知识分散于多格式文档，传统检索难以精准合规获取，影响研发/运维/售后效率。",
       "基于鼎捷雅典娜 ChatFile，以知识中台预训练小模型结合 GPT 大模型，通过行业词典、问题自分析实现知识自学习，支持多轮/跨文档/多语言/多模态交互。",
       ["搭建 ChatFile 问答平台", "知识中台+GPT 大模型", "知识自学习", "研发/运维/售后应用"],
       [{"label": "知识获取", "value": "精准合规、越用越聪明", "kind": "actual"}],
       "为企业打造知识工程体系，精准回答不过度泛化，助力数智化转型。",
       ["大模型", "知识库"], ["鼎捷雅典娜 ChatFile", "GPT 大模型"],
       ["汽车", "知识库", "问答"], featured=False),

    mk("top30-jincheng-360", "天津金城银行：360 智脑大模型赋能金融数智升级",
       {"id": "org-jincheng", "name": "天津金城银行", "size": "medium", "region": "中国", "type": "private"},
       "finance", ["knowledge-base", "agent"], ["信息技术", "客户成功"],
       "360 集团以自研 360 智脑为核心，为天津金城银行创建企业知识库与标准化对话模型，并打造数字员工与虚拟分析师，已实现日均问答1000次、输出文档100篇、会议支持20次。",
       "天津金城银行需围绕场景与办公自动化提升效率，员工信息获取依赖人工。",
       "金融机构知识分散，员工问答与办公辅助缺乏智能化手段。",
       "360 智脑创建企业知识库与标准化对话模型，员工问答快速获取信息；并构建数字员工与虚拟分析师提供智能辅助，覆盖知识问答/多轮对话/阅读理解/推理/推荐等全场景。",
       ["部署 360 智脑", "创建企业知识库", "数字员工与虚拟分析师", "全场景金融能力"],
       [{"label": "日均问答", "value": "1000次", "kind": "actual"},
        {"label": "日均输出文档", "value": "100篇", "kind": "actual"},
        {"label": "日均会议支持", "value": "20次", "kind": "actual"}],
       "构建金融全场景覆盖技术能力，有效提升办公效率与生产力、竞争力。",
       ["大模型", "知识库", "智能体"], ["360 智脑大模型"],
       ["金融", "知识库", "数字员工"], featured=False),

    mk("top30-taikang-hr", "泰康保险：人力资源共享服务中心大模型应用",
       {"id": "org-taikang", "name": "泰康保险集团", "size": "large", "region": "中国", "type": "private"},
       "finance", ["knowledge-base", "workflow"], ["人力资源", "信息技术"],
       "泰康保险基于沃丰科技「大模型+AI知识中台」搭建 HR 智能统一服务平台，通过智能知识搜索、知识库统一管理、员工数据画像，提供便捷 HR 知识服务。",
       "泰康保险 HR 共享服务中心需服务大量员工，知识运营工作量大。",
       "HR 知识全生命周期管理依赖人工，运营效率低、员工问题解决率受限。",
       "基于沃丰科技大模型+AI 知识中台构建 HR 智能平台，赋能知识生产/管理/应用/创新全周期，并支持对接第三方/内部知识库、机器人、客服、营销等系统。",
       ["部署大模型+AI 知识中台", "智能知识搜索", "员工数据画像", "多系统对接"],
       [{"label": "HR 工作效率", "value": "全面提升", "kind": "actual"}],
       "降低知识库运营工作量，提升管理与维护效率，赋能 HR 共享服务中心建设与员工问题解决率。",
       ["大模型", "知识库", "工作流"], ["沃丰科技 AI 知识中台"],
       ["金融", "HR", "知识库"], featured=False),

    mk("top30-tasly-tcm", "天士力：中医药大模型（与华为盘古合作）",
       {"id": "org-tasly", "name": "天士力集团", "size": "large", "region": "中国", "type": "private"},
       "healthcare", ["knowledge-base", "rnd-design"], ["研发与设计", "市场与销售"],
       "天士力与华为盘古大模型合作共建中医药大模型，打造研发增效、中医诊断、天然药物筛选、智能营销、智能诊疗等场景，解决中药信息稀疏离散等研发痛点。",
       "天士力为中药龙头企业，中医药知识宝库庞大但信息稀疏、离散。",
       "传统中药研发信息稀疏离散，研发效率与精度受限。",
       "借助中医药领域优势与华为盘古大模型合作共建垂直大模型，落地研发增效/诊断/药物筛选/营销/诊疗等场景，加速中药创新研发全流程。",
       ["合作共建中医药大模型", "研发增效场景", "天然药物筛选", "智能诊疗与营销"],
       [{"label": "研发效率/精度", "value": "大幅提升", "kind": "actual"}],
       "业界首个中医药垂直领域大模型，加速中药创新与转化，助力中医药研发高质量创新发展。",
       ["大模型", "知识库", "研发"], ["华为盘古大模型"],
       ["医疗", "中医药", "大模型"], featured=False),

    mk("top30-tianyi-risk", "天翼数科：实在 TARS 大模型金融风控应用",
       {"id": "org-tianyi", "name": "天翼数科", "size": "large", "region": "中国", "type": "soe"},
       "finance", ["forecast", "workflow"], ["财务与融资", "信息技术"],
       "实在智能联合天翼数科构建金融风控垂直模型，借助历史数据与大模型语义理解，以人机交互方式实现贷前审核材料审查，整体效率提升300%以上。",
       "天翼数科（中国电信旗下）金融风控贷前审核材料多、交互复杂。",
       "贷前审核流程依赖人工，交互体验与效率有待革命性提升。",
       "将大模型应用于智能风控贷前审核，通过语义理解与人机交互重塑审核流程，并以指令微调、RLHF 训练使模型输出符合预期。",
       ["构建风控垂直模型", "贷前审核材料审查", "人机交互重塑流程", "指令微调+RLHF"],
       [{"label": "审核系统整体效率", "value": "提升300%+", "improvement": "+300%", "kind": "actual"}],
       "实现更智能、自动化的风险控制，提升审核人员工作效率，以大模型承载领域专家知识。",
       ["大模型", "预测分析", "工作流"], ["实在 TARS 大模型"],
       ["金融", "风控", "审核"], featured=False),

    mk("top30-change-ortho", "武汉人工智能研究院：嫦娥工程骨科手术器械智能识别",
       {"id": "org-wuhanai", "name": "武汉人工智能研究院", "size": "large", "region": "中国", "type": "soe"},
       "healthcare", ["quality-inspection", "ops-inspection"], ["生产制造", "研发与设计"],
       "武汉人工智能研究院与九州通基于「紫东太初」全模态大模型打造骨科手术器械智能识别系统，全流程耗时从数小时缩短至1分钟，显著提升作业效能。",
       "骨科手术器械与耗材种类繁多、出入库识别复杂，传统方式耗时长。",
       "复杂植入物与工具识别困难，全流程信息化追踪缺失。",
       "基于千亿参数「紫东太初」全模态大模型实现器械/耗材快速识别、便捷流转、全流程信息化追踪，覆盖术前/配送/术中/术后系统管控。",
       ["部署紫东太初全模态大模型", "器械快速识别", "全流程信息化追踪", "多外科场景适配"],
       [{"label": "全流程耗时", "value": "数小时→1分钟", "improvement": "革命性跨越", "kind": "actual"}],
       "实现智慧识别与全程追踪，引领骨科手术行业数字化转型，可扩展至心外/普外/消毒供应等场景。",
       ["多模态大模型", "智能质检", "运维"], ["紫东太初全模态大模型"],
       ["医疗", "手术", "智能识别"], featured=False),

    mk("top30-xinghuo-insure", "星火保：基于零犀因果大模型的保险个人助理",
       {"id": "org-xinghuo", "name": "星火保", "size": "medium", "region": "中国", "type": "private"},
       "finance", ["sales", "customer-service"], ["市场与销售", "客户成功"],
       "零犀科技基于因果大模型为星火保打造保险个人助理，通过企微/电话/小程序触达用户，实现转化率提升至纯人工的5倍、每单销售成本降低70%。",
       "星火保为保险销售企业，短险业务转化与成本压力大。",
       "传统纯人工转化效率低、成本高，难以精准匹配用户与产品。",
       "以零犀因果大模型打造保险个人助理，具备更强逻辑推理与决策能力，精准匹配用户需求与保险产品，实现业务正向增长。",
       ["部署因果大模型助理", "企微/电话/小程序触达", "需求-产品精准匹配", "业务增长闭环"],
       [{"label": "转化率", "value": "纯人工的5倍", "improvement": "5x", "kind": "actual"},
        {"label": "每单销售成本", "value": "降低70%", "improvement": "-70%", "kind": "actual"}],
       "相较通用模型更懂保险，逻辑与决策能力更强，有效实现保险业务增长、成本下降。",
       ["因果大模型", "销售辅助", "智能客服"], ["零犀因果大模型"],
       ["金融", "保险", "销售"], featured=False),

    mk("top30-yuanbeibei-baby", "元贝贝：华藏大模型智能婴儿床",
       {"id": "org-yuanbeibei", "name": "元贝贝", "size": "small", "region": "中国", "type": "private"},
       "healthcare", ["agent"], ["研发与设计", "客户成功"],
       "元贝贝联合小i机器人打造全球首创「元贝贝智能婴儿床」，基于母婴垂直知识与华藏通用大模型，提供健康监测、异常预测警报、个性化建议与 AI 育儿咨询师「贝贝知道」。",
       "元贝贝聚焦母婴健康，新手父母对智能个性化育儿服务需求强。",
       "母婴健康场景专业度高，传统设备难以提供主动健康管理与专业咨询。",
       "以华藏通用大模型为切入，训练母婴垂直知识库，开发异常预测/警报/建议与 AI 育儿咨询师，打通智能母婴应用场景。",
       ["联合小i机器人", "华藏大模型切入", "母婴健康监测/预测", "AI 育儿咨询师"],
       [{"label": "应用定位", "value": "全球首创智能婴儿床", "kind": "actual"}],
       "以「主动健康」为核心，提供智能化个性化育儿服务，开启数智育儿新时代。",
       ["大模型", "智能体"], ["小i 华藏通用大模型"],
       ["医疗", "母婴", "智能体"], featured=False),

    mk("top30-sunshine-gpt", "阳光保险：阳光正言 GPT 大模型开放平台",
       {"id": "org-sunshine", "name": "阳光保险", "size": "large", "region": "中国", "type": "private"},
       "finance", ["customer-service", "sales"], ["客户成功", "市场与销售"],
       "阳光保险自建大模型平台「阳光正言 GPT」，支持销售/管理/服务三类机器人建设，赋能智能销售、智能核保、智能理赔、智能服务等保险价值链端到端场景。",
       "阳光保险为头部险企，销售/核保/理赔等核心场景亟需大模型深度应用。",
       "保险核心业务（销售/服务/核保/理赔）流程长，传统方式难以端到端赋能。",
       "构建阳光正言 GPT 大模型平台，建设销售/管理/服务三类机器人，覆盖智能销售、核保、理赔、服务等，并具备复杂场景多模态处理能力。",
       ["自建阳光正言 GPT 平台", "三类机器人建设", "智能核保/理赔/服务", "多模态处理"],
       [{"label": "业务覆盖", "value": "销售-核保-理赔-服务端到端", "kind": "actual"}],
       "率先实现大模型在保险领域深度应用，重构核心业务场景，为公司带来弯道超车机会。",
       ["大模型", "智能客服", "销售辅助"], ["阳光正言 GPT（自研）"],
       ["金融", "保险", "大模型平台"], featured=False),

    mk("top30-galaxy-otc", "银河证券：智能场外交易发现平台",
       {"id": "org-galaxy", "name": "银河证券", "size": "large", "region": "中国", "type": "soe"},
       "finance", ["forecast", "agent"], ["财务与融资", "信息技术"],
       "银河证券基于百度文心大模型构建智能场外交易发现平台，将交易询报价全流程自动化，形成从产品理解、需求理解、对话式交易到新增转化的闭环。",
       "银河证券场外衍生品业务询报价流程长，机构客户满意度与效率待提升。",
       "场外衍生品交易规则复杂，传统询报价依赖人工，效率与体验受限。",
       "基于文心大模型构建智能平台，实现询报价端到端自动化与对话式交易，少量样本即可达到不错效果，并提供交易规则智能文档问答。",
       ["构建智能场外交易平台", "询报价全流程自动化", "对话式交易闭环", "交易规则智能问答"],
       [{"label": "样本需求", "value": "少量样本即见效", "kind": "actual"}],
       "提升对客服务效率与机构客户满意度，打通交易规则问答从知识沉淀到应用的闭环。",
       ["大模型", "预测分析", "智能体"], ["百度文心大模型"],
       ["金融", "场外交易", "智能体"], featured=False),

    mk("top30-chinatelecom-kb", "中国电信：知识库问答大模型项目",
       {"id": "org-chinatelecom", "name": "中国电信集团", "size": "extraLarge", "region": "中国", "type": "soe"},
       "telecom", ["knowledge-base"], ["信息技术", "客户成功"],
       "中国电信利用行业大模型、智能文档解析、智能检索与问答技术，针对海量知识库交互对话，帮助用户获取知识、总结摘要、分析归因并自动生成研究报告。",
       "中国电信拥有海量知识库文档，政企客户多样化需求强。",
       "多类型文档与多模态信息解析难，知识获取与问答准确灵活度不足。",
       "使用 OCR/layout/段落分割等多模型解析多类型文档，兼顾多样性/准确性/效率；以智能问答理解意图、逻辑推理、总结归纳，满足政企多样化需求。",
       ["行业大模型+智能文档解析", "多模型解析多类型文档", "智能检索与问答", "自动生成研究报告"],
       [{"label": "问答能力", "value": "意图理解+逻辑推理+归纳", "kind": "actual"}],
       "兼顾文档解析多样性与效率，问答更灵活准确，满足政企客户多样化需求。",
       ["大模型", "知识库", "文档解析"], ["未披露行业大模型"],
       ["通信", "知识库", "文档解析"], featured=False),

    mk("top30-icbc-rnd", "中国工商银行：基于大模型的智能研发体系建设",
       {"id": "org-icbc", "name": "中国工商银行", "size": "extraLarge", "region": "中国", "type": "soe"},
       "finance", ["rnd-design"], ["信息技术", "研发与设计"],
       "中国工商银行利用大模型代码生成/识别/检测/转自然语言等能力，构建覆盖需求、设计、编码、测试、发布的智能研发体系，并以 IDE 插件整合到开发中心。",
       "工商银行研发体系庞大，软件研发效能提升是智能研发重要趋势。",
       "研发全生命周期环节多，代码生成/补全/单测/缺陷检测依赖人工，效能待提升。",
       "构建基于大模型的智能研发体系，覆盖需求-设计-编码-测试-发布全周期，形成代码推演预测、自动生成、检索复用等能力并整合进 IDE 插件。",
       ["构建智能研发体系", "覆盖研发全周期", "代码生成/补全/单测", "IDE 插件整合"],
       [{"label": "研发效能", "value": "有效提高", "kind": "actual"}],
       "代码生成/补全/单测/缺陷检测涌现成熟应用，大模型+研发体系成为智能研发重要趋势。",
       ["大模型", "研发设计"], ["未披露基座大模型"],
       ["金融", "研发", "代码"], featured=False),

    mk("top30-icbc-digital", "中国工商银行：数字员工解决方案",
       {"id": "org-icbc-digital", "name": "中国工商银行", "size": "extraLarge", "region": "中国", "type": "soe"},
       "finance", ["agent"], ["客户成功", "信息技术"],
       "出门问问运用「序列猴子」大模型的数字人技术，1:1复刻工行真人财富顾问，为支行定制私人银行数字财富顾问，并通过训练政策与话术丰富专业知识。",
       "工商银行财富顾问服务覆盖面有限，知识更新快。",
       "财富顾问难以覆盖所有支行，知识库更新与业务数据分析需智能化。",
       "以序列猴子大模型数字人技术复刻真人财富顾问，定制数字财富顾问，持续更新知识库与业务数据分析，打造“问不倒”的数字顾问。",
       ["部署序列猴子数字人", "1:1 复刻财富顾问", "定制支行数字顾问", "知识库持续训练"],
       [{"label": "服务形态", "value": "“问不倒”数字财富顾问", "kind": "actual"}],
       "实现知识库持续更新与业务数据分析，打通服务闭环，未来可短视频/直播宣传。",
       ["大模型", "智能体", "数字人"], ["出门问问 序列猴子大模型"],
       ["金融", "数字员工", "财富顾问"], featured=False),

    mk("top30-abchina-chatabc", "中国农业银行：ChatABC 金融大模型",
       {"id": "org-abchina", "name": "中国农业银行", "size": "extraLarge", "region": "中国", "type": "soe"},
       "finance", ["knowledge-base", "customer-service"], ["信息技术", "客户成功"],
       "中国农业银行基于开源技术端到端自研金融 AI 大模型 ChatABC，形成智能客服/营销/风控/决策/研发/办公/安全/运维/三农九大主题场景域、30+场景同步建设。",
       "农业银行作为国有大行，需自主可控的金融大模型支撑多场景。",
       "金融领域知识理解、内容生成与安全问答需求强，场景分散。",
       "基于开源技术全流程自研 ChatABC，以「大模型+」生态建设九大主题场景域，在智能研发/网络安全/智慧三农/智慧信贷等领域发挥价值。",
       ["端到端自研 ChatABC", "九大主题场景域", "30+ 场景同步建设", "智慧三农等落地"],
       [{"label": "场景规模", "value": "九大域30+场景", "kind": "actual"}],
       "重点着眼金融知识理解/内容生成/安全问答，智慧三农以图像感知应用于畜牧盘点、状态监控，已在全国多家牧场推广。",
       ["大模型", "知识库", "智能客服"], ["农行 ChatABC（自研）"],
       ["金融", "大模型", "三农"], featured=False),

    mk("top30-cpic-audit", "中国太保：基于大模型的审计数字劳动力",
       {"id": "org-cpic", "name": "中国太保", "size": "extraLarge", "region": "中国", "type": "private"},
       "finance", ["workflow", "agent"], ["财务与融资", "信息技术"],
       "中国太保以数字劳动力为突破口开展保险大模型应用，打造数字员工基座大模型，实现对业务人员系统性建模，构建审计检查、公文质检、资讯问答等多名审计数字员工。",
       "中国太保审计工作量大、人力不足，传统 AI 仅解决特定环节问题。",
       "审计人力不足，传统 AI 难理解思考并解决不特定任务。",
       "以数字员工基座大模型对齐真实员工思想/行动/职业能力，构建审计数字员工，通过人机编队方式提升审计效率与准确率。",
       ["打造数字员工基座大模型", "业务人员系统性建模", "审计数字员工", "人机编队工作"],
       [{"label": "审计效率/准确率", "value": "助力提高", "kind": "actual"}],
       "数字员工与真实员工人机编队，助力提高审计效率与准确率，填补审计人力不足。",
       ["大模型", "工作流", "智能体"], ["未披露基座大模型"],
       ["金融", "审计", "数字员工"], featured=False),

    mk("top30-ziroom-cs", "自如：基于AI大模型的客服问题归因与服务质量分析",
       {"id": "org-ziroom", "name": "自如 ziroom", "size": "large", "region": "中国", "type": "private"},
       "software-internet", ["customer-service", "workflow"], ["客户成功", "信息技术"],
       "自如运用循环智能千亿参数「千循」大模型，对客服交互数据深度挖掘，自动识别问题根因、评估客服响应质量与效率，并支持20万字超长上下文低幻觉。",
       "自如作为长租公寓平台，客服交互量大，需提升整体服务质量。",
       "客服问题诉求总结、根因分析与情感状态评估依赖人工，效率低。",
       "以千循大模型分析沟通数据，实现问题快速总结、解决方案总结、情感分析、根因分析与客户心声汇总，专设指令工程降低幻觉。",
       ["部署千循大模型", "客服问题根因分析", "情感与质量评估", "指令工程降幻觉"],
       [{"label": "上下文窗口", "value": "20万字超长", "kind": "actual"}],
       "实现客户问题自动化归因与服务质量量化，提升整体服务质量的策略优化能力。",
       ["大模型", "智能客服", "工作流"], ["循环智能 千循大模型"],
       ["互联网", "客服", "归因分析"], featured=False),
]


def main():
    out = []
    for c in CASES:
        rec = build(c)
        out.append(rec)
        print(f"  [OK] {rec['title']}  (slug={rec['slug']}, industry={rec['industry']['id']}, scenarios={[s['id'] for s in rec['scenarios']]})")
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"\n已生成 {len(out)} 条案例 -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
