import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { nanoid } from "nanoid";
import { z } from "zod";
import { getAdminSession } from "@/lib/auth/dal";
import { writeAuditLog } from "@/lib/audit";
import { getIndustry, getScenario } from "@/lib/catalog";
import { getDb, isMongoConfigured } from "@/lib/db/mongodb";
import type { CaseStudy, ContentStatus, OutcomeStatus, ConfidenceLevel } from "@/lib/types";

export const caseInputSchema = z.object({ slug: z.string().regex(/^[a-z0-9-]+$/).max(120).optional(), title: z.string().min(4).max(200), organization: z.string().min(1).max(150), organizationSize: z.string().min(1).max(50), industry: z.string().min(1), scenario: z.string().min(1), businessFunction: z.string().min(1).max(50), summary: z.string().min(10).max(1000), background: z.string().min(10).max(5000), problem: z.string().min(10).max(5000), solution: z.string().min(10).max(8000), implementationSteps: z.array(z.string().max(500)).max(20).default([]), duration: z.string().max(200).default("未披露"), cost: z.string().max(200).default("未披露"), roi: z.string().max(300).default("未披露"), results: z.array(z.object({ label: z.string(), value: z.string(), kind: z.enum(["actual", "expected", "estimated", "undisclosed"]).default("undisclosed") })).max(12).default([]), risks: z.string().max(3000).default("需结合企业实际数据、权限和人工复核机制评估。"), outcomeStatus: z.enum(["success", "partial", "failure", "undisclosed"]), confidence: z.enum(["high", "medium", "pending"]), contentStatus: z.enum(["draft", "duplicate_review", "in_review", "published", "rejected", "archived"]), sourceTitle: z.string().min(2).max(300), sourcePublisher: z.string().min(1).max(150), sourceUrl: z.url().optional().or(z.literal("")), sourcePublishedAt: z.string().max(30).optional(), sourceSupports: z.array(z.string().max(200)).max(20).default([]), editorComment: z.string().max(2000).default("建议先核对业务基线、样本质量和人工兜底流程。"), suitableFor: z.string().max(500).default("业务流程相近且具备基础数据的企业"), prerequisites: z.string().max(500).default("明确业务负责人、样本和验收指标") });

function makeSlug(title: string, requested?: string) { if (requested) return requested; const digest = createHash("sha256").update(title).digest("hex").slice(0, 8); return `case-${digest}`; }
export async function POST(request: Request) { const session = await getAdminSession(); if (!session) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); if (!isMongoConfigured()) return NextResponse.json({ error: "请先配置 MongoDB 后再保存案例" }, { status: 503 }); const parsed = caseInputSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "案例字段不完整", fields: parsed.error.flatten().fieldErrors }, { status: 400 }); const value = parsed.data; const industry = getIndustry(value.industry); const scenario = getScenario(value.scenario); if (!industry || !scenario) return NextResponse.json({ error: "行业或场景不在受控词表中" }, { status: 400 }); const now = new Date().toISOString(); const id = nanoid(16); const item: CaseStudy = { id, slug: makeSlug(value.title, value.slug), title: value.title, organization: { id: `org-${createHash("sha256").update(value.organization.trim().toLowerCase()).digest("hex").slice(0, 12)}`, name: value.organization, size: value.organizationSize }, industry, scenarios: [scenario], businessFunctions: [value.businessFunction], summary: value.summary, background: value.background, problem: value.problem, solution: value.solution, implementationSteps: value.implementationSteps, duration: value.duration || "未披露", cost: value.cost || "未披露", results: value.results.length ? value.results : [{ label: "项目效果", value: "未披露", kind: "undisclosed" }], roi: value.roi || "未披露", risks: value.risks, editorComment: { suitableFor: value.suitableFor, prerequisites: value.prerequisites, priority: "条件具备后开展", text: value.editorComment }, implementers: [], outcomeStatus: value.outcomeStatus as OutcomeStatus, contentStatus: value.contentStatus as ContentStatus, confidence: value.confidence as ConfidenceLevel, sources: [{ id: nanoid(14), title: value.sourceTitle, publisher: value.sourcePublisher, type: "media", url: value.sourceUrl || undefined, publishedAt: value.sourcePublishedAt || undefined, collectedAt: now, accessibility: "available", supports: value.sourceSupports }], featured: false, views: 0, publishedAt: value.contentStatus === "published" ? now : "", updatedAt: now };
  const db = await getDb(); try { await db.collection<CaseStudy>("cases").insertOne(item); } catch (error) { if (error instanceof Error && error.message.includes("duplicate key")) return NextResponse.json({ error: "Slug 已存在，请修改后重试" }, { status: 409 }); throw error; } await writeAuditLog({ actor: session.user?.email ?? "admin", action: "case.create", entityType: "case", entityId: id, after: item }); return NextResponse.json({ ok: true, id, slug: item.slug }); }
